### ISSUE TITLE
Syntax on electrode positions

### ISSUE THREAD

**Issue by balou1902** [MetaCell/NetPyNE-UI#103]
Hello,

I modelled a ball-and-stick neuron so I guess that the soma is the center (0,0,0). What I want to do next is to set a electrode located at (0,50,250) (for example).

So I go in Simulation configuration > Record > Add new Record LFP electrode locations to type the coordinates. However... what is the syntax ?

I tried many <[0,50,250] or (0,50,250) ... > but I only get an error :  "Only comma separated float number are allowed"..

Thanks in advance

Harry

**Comment by rodriguez-facundo** [comment]
Hi Harry, I think what you are looking for it just. 0,50,250 .  no [] or () are required

**Comment by balou1902** [comment]
Yes it works.

Thank your for your quick answer !

**Comment by rodriguez-facundo** [comment]
No problem =)
