### ISSUE TITLE
not able to download Virtual box image file.

### ISSUE THREAD

**Issue by INNFINITEMINDS** [MetaCell/NetPyNE-UI#111]

**Comment by INNFINITEMINDS** [comment]
eed to download and install Virtual Box in your computer and download as well the VM image from NetPyNE-UI VM images (pick the latest version).



=======================================
i was not able to download .vdi file.
please provide it .
awaiting for your responce .
thanks

**Comment by INNFINITEMINDS** [comment]
===================================================
https://github.com/MetaCell/NetPyNE-UI/wiki/Virtual-Machine-Installation
==================================================
this is the link

**Comment by INNFINITEMINDS** [comment]
![screenshot 48](https://user-images.githubusercontent.com/28722237/53086215-8830bb80-34b9-11e9-9979-018a7451ee95.png)
![image](https://user-images.githubusercontent.com/28722237/53086371-d34ace80-34b9-11e9-8811-31b0f1bc2aa1.png)

**Comment by ddelpiano** [comment]
Hi INNFINITEMINDS, 

the latest image is available at this link [https://drive.google.com/open?id=1Pjd8zLXOf6_6fbnsjmL48C_uAIVYBYSP](https://drive.google.com/open?id=1Pjd8zLXOf6_6fbnsjmL48C_uAIVYBYSP) . 
Feel free to ask if you will experience any problem.

Kind regards,
Dario
