### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by salvadord** [MetaCell/NetPyNE-UI#112]
Sergio Solinas:
"Hi Salvador,
anaconda3 is installed.
pip install of netpyne worked.
pip install of netpyne-ui failed.
I could install Docker, download the docker image.
After starting the docker image I cannot connect to the localhost:8888 port.
I'll see what I can do tomorrow.
Ciao
Sergio"

**Comment by lrebscher** [comment]
I guess the port was not published with `-p 8888:8888`, if you use this option it should work. I added Docker instructions to the README, so I see this issue as closed.
