### ISSUE TITLE
.vdi file missing

### ISSUE THREAD

**Issue by wwlytton** [MetaCell/NetPyNE-UI#114]
Can't find netpyne.vdi for virtualbox in the .zip file

**Comment by ddelpiano** [comment]
Hi @wwlytton , 
Could you please point me to the link you used ?
You could try with this archive linked here [https://drive.google.com/open?id=1Pjd8zLXOf6_6fbnsjmL48C_uAIVYBYSP](https://drive.google.com/open?id=1Pjd8zLXOf6_6fbnsjmL48C_uAIVYBYSP) and, once extracted the zip file, you will see the file netpyne_ui_latest.vdi.
