### ISSUE TITLE
expand jupyter tab and can't unexpand

### ISSUE THREAD

**Issue by wwlytton** [MetaCell/NetPyNE-UI#115]

**Comment by wwlytton** [comment]
hit the up-arrow in the "Python" jupyter tab and filled the screen with the nb but then couldn't figure out how to get back to viewing the model??

made the mistake of trying 'reload' page and lost all my work ... maybe a warning if possible?

**Comment by ddelpiano** [comment]
hi @wwlytton ,

I tried to reproduce the behaviour and I can confirm that is a bug, we will work this one out in the next release.

Thanks,
Dario

**Comment by ddelpiano** [comment]
related to the old UI, already solved with flexlayou
