### ISSUE TITLE
get "notebook.ipynb is not trusted" error

### ISSUE THREAD

**Issue by wwlytton** [MetaCell/NetPyNE-UI#117]
[W 13:31:48.633 NotebookApp] Notebook notebook.ipynb is not trusted

then fails to load   "Loading is taking longer than usual, either a large amount of data is being loaded or bandwidth is limited"

but never finishes

**Comment by wwlytton** [comment]
solved that nb problem with `jupyter trust notebook.ipynb`

but program is still hanging

**Comment by ddelpiano** [comment]
hi @wwlytton , could you provide us the notebook you used to trigger this issue?
Thanks!
