### ISSUE TITLE
Installation globally disables jupyter notebook menu

### ISSUE THREAD

**Issue by cliffckerr** [MetaCell/NetPyNE-UI#118]
Following the installation instructions here:
https://github.com/Neurosim-lab/NetPyNE-UI/wiki/Pip-installation

This disables the Jupyter notebook menus for _all_ notebooks on the system. It would be preferable if this could be part of `NetPyNE-UI`, since it is annoying to have to type `jupyter nbextension disable --py jupyter_geppetto ` every time to get these back for other notebooks. 

If this isn't possible, at minimum this should be mentioned in the documentation, since I (and others, including Joe, the NetPyNE tutor here :P) thought Geppetto installation had just broken Jupyter...

cc @salvadord @tarelli

**Comment by tarelli** [comment]
Hi Cliff, what we recommend is to use a Python virtual environment to avoid any of that https://github.com/MetaCell/NetPyNE-UI/wiki/Pip-installation#setting-up-a-python-virtual-environment

We'll update this bi:

```
If you would like to setup a Python virtual environment (useful if you already have a different version of some of the libraries installed in your system and you want to avoid conflicts) jump here before installing NetPyNE UI.
``` to make ir even more explicit.

**Comment by tarelli** [comment]
Done https://github.com/MetaCell/NetPyNE-UI/wiki/Pip-installation#install-using-pip

**Comment by pgleeson** [comment]
Snap: https://github.com/MetaCell/NetPyNE-UI/issues/76

**Comment by cliffckerr** [comment]
@tarelli I know, but not everyone wants to have a separate virtual environment for every workflow :) If you want to disable the menu bar and header would it be possible to just add this to the `exec jupyter notebook --NotebookApp.default_url=/geppetto --NotebookApp.token='' --library=netpyne_ui` command rather than setting it as a global configuration?

**Comment by cliffckerr** [comment]
@pgleeson Sorry, I didn't see that, I agree it's a duplicate issue!
