### ISSUE TITLE
Use normal file save for exported code

### ISSUE THREAD

**Issue by cliffckerr** [MetaCell/NetPyNE-UI#119]
Currently, if you export your NetPyNE-UI model to code, it will automatically put it in the netpyne_workspace folder. It would be better if it opened a standard JavaScript `saveAs` dialog box, since (a) you might want to save multiple copies with different names, (b) if running remotely (e.g. netpyne.org/gui) then it get saves to a remote server you don't have access to :)

**Comment by ddelpiano** [comment]
Already part of the upload/download mechanism implemented, this is on the roadmap to be again improved according to the new design. Closing this since we already addressing this in the asana board.
Thx
