### ISSUE TITLE
Error on Jupyter notebook when selecting "plot traces" after running simulation 

### ISSUE THREAD

**Issue by jamesjun** [MetaCell/NetPyNE-UI#121]
# Error log

otTraces():
 Parameterized generics cannot be used with class or instance checks
(<class 'TypeError'>, TypeError('Parameterized generics cannot be used with class or instance checks',), <traceback object at 0x11f6dcdc8>)

# installed versions
(neuron) jamesjun@C02YJ0JQJHD5:~$ pip list
Package             Version
------------------- ---------
appnope             0.1.0
attrs               19.1.0
backcall            0.1.0
bleach              3.1.0
certifi             2019.6.16
cycler              0.10.0
decorator           4.4.0
defusedxml          0.6.0
entrypoints         0.3
future              0.17.1
html5lib            1.0.1
ipykernel           5.1.1
ipython             7.6.1
ipython-genutils    0.2.0
ipywidgets          7.4.1
jedi                0.13.3
Jinja2              2.10.1
jsonschema          3.0.1
jupyter             1.0.0
jupyter-client      5.2.4
jupyter-console     5.2.0
jupyter-core        4.5.0
jupyter-geppetto    0.4.2
jupyterlab          0.35.5
jupyterlab-server   0.2.0
kiwisolver          1.0.1
lxml                4.2.4
MarkupSafe          1.1.1
matplotlib          2.2.3
matplotlib-scalebar 0.6.0
mistune             0.8.4
nbconvert           5.5.0
nbformat            4.4.0
netpyne             0.9.1.1
netpyne-ui          0.5.2
NEURON              7.7
notebook            5.7.8
numpy               1.15.1
ordered-set         3.0.1
pandas              0.24.2
pandocfilters       1.4.2
parso               0.5.0
pexpect             4.7.0
pickleshare         0.7.5
pip                 19.1.1
prometheus-client   0.7.1
prompt-toolkit      2.0.9
ptyprocess          0.6.0
pyecore             0.8.7
pygeppetto          0.4.2
Pygments            2.4.2
pyparsing           2.2.0
pyrsistent          0.14.11
python-dateutil     2.8.0
pytz                2018.5
pyzmq               18.0.0
qtconsole           4.4.1
scipy               1.1.0
Send2Trash          1.5.0
setuptools          39.0.1
simplegeneric       0.8.1
six                 1.12.0
terminado           0.8.2
testpath            0.4.2
tornado             6.0.3
traitlets           4.3.2
wcwidth             0.1.7
webencodings        0.5.1
wheel               0.33.4
widgetsnbextension  3.4.1

**Comment by ddelpiano** [comment]
hi @jamesjun, could you provide us the jupyter notebook to reproduce this issue please?
