### ISSUE TITLE
Installation issue - spinning star

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/NetPyNE-UI#122]
Similar to the issue here: https://github.com/MetaCell/nwb-explorer/issues/75, I just have a constantly spinning star following smooth installation using a new env (py3.6) in conda on Ubuntu:

![image](https://user-images.githubusercontent.com/1556687/61963229-093d3300-afc3-11e9-8c1f-5eade0b6a32b.png)

**Comment by pgleeson** [comment]
Also no longer an issue. Building/running the development branch works fine for me locally. 

The locally built development branch does seem to be a bit behind some of the demos shown during the sprint though. @ddelpiano @filippomc I'd be happy to test a (pre)prerelease of a stable-ish NetpyneUI, when you think it's ready, not really from the point of view of the gui updates, but to check the current simulation building/running capabilities and plan updating/interacting with NeuromL tools.

**Comment by ddelpiano** [comment]
Hi @pgleeson, sorry about the delay here, this has been sitting on my mind for 2 weeks but I was just finding the time to reply to this :-).
We allocated a slot for the next netpyne sprint to look into this and test/update the GUI with the latest version of the library, so it will happen somewhere in the next 2 weeks, we will let you know once this will up and running. Thx
