### ISSUE TITLE
Error on pip install

### ISSUE THREAD

**Issue by bagnall-lab** [MetaCell/NetPyNE-UI#123]
Mac OS 10.14, Python 3.8 (installed from python.org, not homebrew). Tried to install with
`pip3 install netpyne_ui`
and mostly the installation was going ok, then got to:

`Collecting matplotlib==2.2.3 (from jupyter_geppetto==0.4.2->netpyne_ui)
  Downloading https://files.pythonhosted.org/packages/eb/a0/31b6ba00bc4dcbc06f0b80d1ad6119a9cc3081ecb04a00117f6c1ca3a084/matplotlib-2.2.3.tar.gz (36.8MB)
     |████████████████████████████████| 36.8MB 68.4MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/v1/wq55p63158j2j382s__686b40000gn/T/pip-install-tor74wt6/matplotlib/setup.py'"'"'; __file__='"'"'/private/var/folders/v1/wq55p63158j2j382s__686b40000gn/T/pip-install-tor74wt6/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/v1/wq55p63158j2j382s__686b40000gn/T/pip-install-tor74wt6/matplotlib/
    Complete output (108 lines):
    IMPORTANT WARNING:
        pkg-config is not installed.
        matplotlib may not be able to find some of its dependencies
`

Any suggestions?

**Comment by bagnall-lab** [comment]
I then used
`brew install freestyle`
`brew install pkg-config`

and then re-ran `pip3 install netpyne_ui`
Things were going better until again barfing on matplot lib:

> Running setup.py install for matplotlib ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/v1/wq55p63158j2j382s__686b40000gn/T/pip-install-1m2gasd1/matplotlib/setup.py'"'"'; __file__='"'"'/private/var/folders/v1/wq55p63158j2j382s__686b40000gn/T/pip-install-1m2gasd1/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/v1/wq55p63158j2j382s__686b40000gn/T/pip-record-r41figue/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/v1/wq55p63158j2j382s__686b40000gn/T/pip-install-1m2gasd1/matplotlib/
    Complete output (37 lines):
    ============================================================================
    Edit setup.cfg to change the build options

(truncated rest of message)
Not sure where to go from here.

**Comment by rodriguez-facundo** [comment]
I also had problems with python 3.8. I had to go back to python 3.7.

**Comment by bagnall-lab** [comment]
Ok thanks, that solved it! 

Now I need to get it to find NEURON--I already had NEURON 7.7 installed and I didn't want to potentially break it by installing 7.6 per the instructions, but in the UI got:
`ModuleNotFoundError: No module named 'neuron'`
so maybe I do have to go back to 7.6? I have an ongoing project using 7.7 though, so I'm concerned about breaking it.

**Comment by rodriguez-facundo** [comment]
If I remember correctly, I installed neuron using the source code from github. Then after running `./configure`, `make` and `make install` I had to go to `src/nrnpython` and run `python setup.py install` so that I get neuron working in python.
Maybe if you run that last bit again with this new python 3.7, then you get it working, but I dont know the details of your setup 🔨 ⚠️

**Comment by bagnall-lab** [comment]
FYI for any users going down this path, that if they are installing from github, they need autoconf, automake, and libtool installed first per the info here....
https://www.neuron.yale.edu/neuron/download/compilestd_osx
I was able to install NEURON 7.6.2 up through 
`./build.sh`
`./configure --without-x --with-nrnpython=python3 --without-paranrn --prefix="/path_where_you_installed_nrn/" --without-iv`

but now in response to
`make --silent -j4`
it's returning:

> Making all in src
Making all in memacs
libtool: link: `libmemacs_la-ansi.lo' is not a valid libtool object
make[3]: *** [libmemacs.la] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

I made sure libtool was as up to date as possible (version 2.4.6) but that didn't resolve the issue. Is it related to the non-MPI install??

**Comment by rodriguez-facundo** [comment]
Is not the first time I hear this issue. After successfully installing python-neuron interpreter in one environment, trying to installing it again in a second environment gives some errors. Things I would try:
- running just `python setup.py install` (not the full installation, just the python part).
- If that does not work, then deleting what was installed in `--prefix=`, and deleting what was compiled in `pwd`, then install neuron again + install python interpreter again.
