### ISSUE TITLE
Update/remove update.py?

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/NetPyNE-UI#149]
The Readme refers to 

    python update.py

in utlilties to update the sources, but this doesn't run. Is the update not managed now in install.py? Should it be?

**Comment by lrebscher** [comment]
update.py is outdated, I removed it and updated the README accordingly ( 95889fb07432c2043904f20d02bf1166aa194668 )
The update is currently not managed in install.py, so you have to cd into each repository and run `git pull` or delete the sources and run install.py again. I will tackle this while working on the next feature.

**Comment by pgleeson** [comment]
Thanks @lrebscher. Getting it as easy as possible to install/update would be great for building and helping the userbase and finding any issues.

**Comment by pgleeson** [comment]
Fixed in development, closing.
