### ISSUE TITLE
regarding docker installation

### ISSUE THREAD

**Issue by INNFINITEMINDS** [MetaCell/NetPyNE-UI#169]
The installation and running the docker container instructions are missing .or i am unable to find out .
awaiting for response.

Thanks,
Arpit

**Comment by lrebscher** [comment]
Hey Arpit,

thank you for pointing this out, I just added them to the README.

Execute the commands below from the project directory to run NetPyNe-UI in a Docker container:

```bash
docker build . -t netpyne-ui
docker run -it -p 8888:8888 netpyne-ui
```
