### ISSUE TITLE
Avoid overriding global Jupyter notebook theme

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/NetPyNE-UI#185]

**Comment by pgleeson** [comment]
This is happenning to me too ... Also when I build https://github.com/MetaCell/nwb-explorer (using a dedicated conda environment)
Previously had been an issue with NetPyNE-UI (https://github.com/MetaCell/NetPyNE-UI/issues/76), but this time a file is being created: ~/.jupyter/custom/custom.css which is global and impacts all other envs, Python 2 & 3.

**Comment by lrebscher** [comment]
@pgleeson  my last commit #6163857 should resolve this issue for NetPyNe-UI, it now sets a custom config directory instead of using the default one
