### ISSUE TITLE
Add version info for core NetPyNE (and Neuron?) in About box

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/NetPyNE-UI#191]
Also a bit difficult to read NPUI info:
<img width="614" alt="Screenshot 2021-01-13 at 17 22 22" src="https://user-images.githubusercontent.com/1556687/104486629-ebeb9280-55c3-11eb-8ca6-ab3b218f6dd3.png">

**Comment by Muhaddatha** [comment]
![image.png](https://images.zenhubusercontent.com/6092c4168a6d77eedd5f4505/0920843b-6f45-490b-aa77-9eb717983c99)

**Comment by pgleeson** [comment]
Looks good @Muhaddatha, but for me the purple is still a bit unclear/too dark. Maybe a few shades lighter? It's not used elsewhere in the UI much (as far as I can see), so shouldn't impact other graphical elements much.

**Comment by Muhaddatha** [comment]
Sure, I will speak to Lucas and see what shade would look better for the text.

**Comment by lrebscher** [comment]
The color is our secondary color in the theme and is reused across multiple components (e.g. Populations, Hover color for add button, Loading Spinner + text)

We're waiting with this one until our designer makes a recommendation for a new color :)

**Comment by lrebscher** [comment]
@Muhaddatha  we'll go with our primary color (main pink)

**Comment by pgleeson** [comment]
I was originally going to suggest that, but the rest of the pink text are links. However, you could link from these to the repos for the individual packages.

**Comment by salvadord** [comment]
Neuron -> NEURON

NetPyNE-UI is being developed by the State University of New York Downstate ([Dura-Bernal](http://dura-bernal.org) Lab) in collaboration with:
