### ISSUE TITLE
Third simulation run of same model causes 3D Representation to vanish

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/NetPyNE-UI#198]
**Reproduction**
* Import Tutorial 1
* Model > Simulate Network
* Model > Simulate Network 
* Model > Simulate Network

**Actual**
3D Representation plot is empty after third run.

**Expected**
Plot still shows content

<img width="1669" alt="Bildschirmfoto 2021-02-08 um 18 54 50" src="https://user-images.githubusercontent.com/7281685/107261148-3fc08e80-6a3f-11eb-8d8f-e6e8f1c09002.png">

**Comment by lrebscher** [comment]
NetPyneInstantiated.js wraps Canvas.js from geppetto.

The Canvas does some automatic update in the background on geppetto model change and adds new instances to the Canvas, but it adds new instances instead of resetting the instances. When a user creates the network, we have a completely new network, we don't want to keep old instances.

Currently the broken hack that was implemented is resetting what 3DCanvas does internally (adding new instances).
In middleware.js, we dehydrateCanvas() to reset the instances, this works only if we move from Edit > Explore since NetPyneInstantiated.js widget will run updateInstances() on componentDidMount() once to populate the plot again.

Since the updateIntances() run only on componentDidMount, this hack is doomed to fail when the widget is already mounted and needs to be updated. 

We have to ensure that Canvas is also populated with instances again when running CREATE_NETWORK when already being in the Explore view. E.g. ensuring that updateInstances() will run.

However, the actual problem here is that Canvas seems to add new instances without removing the old ones,  While this might be wanted in certain situation, it is undesired behavior in Netpyne.

We should either extend the Canvas to enable it to reset instances before adding new ones OR triggering the Geppetto Instance_deleted event in Netpyne-UI to ensure that old instances will be removed.

**Comment by filippomc** [comment]
One thing to consider is to use the new canvas from geppetto-meta, which is rewritten in a more reacty way, so the magic around the model that is causing trouble here is removed.

**Comment by ddelpiano** [comment]
@enicolasgomez could you first confirm if the issue is still present, if yes, let's discuss next action together since I don't know if you have enough bandwidth in this sprint.

**Comment by enicolasgomez** [comment]
@ddelpiano interestnigly enough, the first time that the model is simulated the 3d model renders fine. In the 2nd attempt to simulate, it errors out with the `RuntimeError: hoc error` returned by #213.

Will need to further look into it.

```
~/Work/MetaCell/NetPyNE-UI/src/netpyne/netpyne/cell/compartCell.py in associateGid(self=compartCell0, threshold=None)
    569             if sim.cfg.createNEURONObj:
    570                 if hasattr(sim, 'rank'):
--> 571                     sim.pc.set_gid2node(self.gid, sim.rank) # this is the key call that assigns cell gid to a particular node
        sim.pc.set_gid2node = ParallelContext[6].set_gid2node()
        self.gid = 0
        sim.rank = 0
    572                 else:
    573                     sim.pc.set_gid2node(self.gid, 0)

RuntimeError: hoc error
```

**Comment by enicolasgomez** [comment]
@ddelpiano after doing a clean install I was not able to replicate this issue anymore, I suspect there was some left over from #213 as it was exactly the same error. I will continue looking at that one an test this one time to time to see if it can be reproduced.
