### ISSUE TITLE
Export as python script: suggested filename not used

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/NetPyNE-UI#201]
The File -> Export -> To python option asks for a filename (default output), but a name like NetPyNE_init_Wed_10_Feb_2021_09_26_52_GMT.py is used instead.

**Comment by lrebscher** [comment]
Can confirm, need to return filename in [exportHLS](https://github.com/MetaCell/NetPyNE-UI/blob/d44e88174a1c7198348ebc35a3563e66145bad2f/netpyne_ui/netpyne_geppetto.py#L640) method and use it in the frontend in [`downloadPythonResponse`](https://github.com/MetaCell/NetPyNE-UI/blob/d44e88174a1c7198348ebc35a3563e66145bad2f/webapp/redux/middleware/utils.js#L35)
