### ISSUE TITLE
NeuroML- Importing cell model in GUI

### ISSUE THREAD

**Issue by salvadord** [MetaCell/NetPyNE-UI#202]
Richard Gerkin  1:54 PM
Hi Salvador, quick bug report here (but let me know where to put these in general):
I was showing my student how to get things from NeuroML-DB and we decided to put something into NetPyne.  I searched for CA1 Pyramidal Cell on NeuroML-DB and got this model as the first hit: https://neuroml-db.org/model_info?model_id=NMLCL001633.  I clicked “Download NEURON version” and got a zip file (containing hoc and mod files) which I uploaded directly to NetPyne GUI via File / Workspace / Upload.  I then tried to import this from the workspace via Cell Types / Cell / Import cell template from file…, which conveniently also unzipped it for me in the uploads subdirectory.  In the menu, I selected /home/jovyan/work/NetPyNE-UI/netpyne_workspace/uploads/ivycell.hoc as the path to the file, and /home/jovyan/work/NetPyNE-UI/netpyne_workspace/uploads as the path to the mod files, as they were unzipped right there.  I checked compile mod files as I figured this would be needed.  I then got the ubiquitous “Error while importing the NetPyNE cell template” error message.

**Comment by enicolasgomez** [comment]
@ddelpiano errors out wih `AttributeError: 'hoc.HocObject' object has no attribute ''` - might be a parsing issue at load time. Checking into it.

**Comment by enicolasgomez** [comment]
@ddelpiano @salvadord @filippomc 

so the attribute which is being passed empty is "Cell template/class name" which is indeed one of the parameters requested by the GUI. So two things here:

- First, this parameter should be validated as mandatory so the python stack doesn't crash
- Second, seems like these cell name should match one of the defined names within the HOC file. Looking at the file, the root one matches the file name. Not sure if this is a convention and can be used as-is or if we should parse the hoc file and populate a combo with the hoc file's content.

When I passed ivycell to this param netpyne started loading the schemma.

**Comment by enicolasgomez** [comment]
As discussed in the meeting, we will need to parse begintemplate ivycell within the hoc file
