### ISSUE TITLE
JSON generated from NeuroML export fails to 3D display/simulate

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/NetPyNE-UI#213]
I've created a simple example of a JSON model file which was generated from a NeuroML model: [HHCellNetwork.txt_data.json](https://github.com/OpenSourceBrain/NetPyNEShowcase/blob/master/NetPyNE/UI/HHCellNetwork.txt_data.json). The steps to generate/test this can be seen here: [test_all.sh](https://github.com/OpenSourceBrain/NetPyNEShowcase/blob/master/NetPyNE/UI/test_all.sh).

This can be loaded into NetPyNE UI successfully (local install of development branch), the cell/pop properties show up in the Edit view, but when Create Network is pressed, it hangs on the spinning logo:

<img width="1679" alt="Screenshot 2021-11-30 at 17 56 31" src="https://user-images.githubusercontent.com/1556687/144101710-03152a81-8df0-4ca4-8415-d733db7aebfb.png">

Being able to load this very simple example is a crucial step to using  NetPyNE-UI with NeuroML

**Comment by lrebscher** [comment]
I can confirm this issue, in a first inspection I could narrow it down to the `originalFormat: "NeuroML2"` attribute that is set for a population and cell. I compared the json to a similar json model that I created in netpyne-UI. After removing originalFormat and simplifying cell attributes, I could see the 3DCanvas again.

Netpyne handles cell and population type differently depending on `originalFormat`, it is not clear to me yet what implication it has for the Geppetto cell instances that are used as input for the 3DCanvas.

I don't get any stack trace or error message.

Fixing this issue will take more time.

**Comment by pgleeson** [comment]
@lrebscher Thanks for the update. I'm looking into this. It's possible that the `originalFormat: "NeuroML2"` can be removed in JSON export if the file is intended to go back into NetPyNE, as it should all be "pure" NetPyNE at that stage.

**Comment by lrebscher** [comment]
We have to check if this is solved by #243

**Comment by pgleeson** [comment]
@ddelpiano @enicolasgomez This is still a blocking issue in getting NeuroML generated JSON files loaded into NetPyNE-UI. I've updated the top comment with a link to the latest test Json and a screnshot of the hung screen. 

It is possibly related to the issue at https://github.com/MetaCell/NetPyNE-UI/issues/374.

It would be great if you could test it out too, as this is valid json for netpyne and will be important to fix for the netpyne format too.

**Comment by ddelpiano** [comment]
discussed during the latest sprint, please look at the recording around 30mins~ since there are some notes regarding this.

**Comment by enicolasgomez** [comment]
@pgleeson @ddelpiano added a testing case `test_netpyne_exported_model_1` on the backend testing case that would replicate the case.  The error is `run time error - ad hoc error` and the ofending method is `compartCell.associateGid` when calling *set_gid2node*.

In latest version the UI doesn't seem to hang up and errors out gracefully.

**Comment by enicolasgomez** [comment]
Get stable release for netypne / netpyne-ui and see if it's still broken in there

**Comment by enicolasgomez** [comment]
Run from netpyne python console to compare with the script

**Comment by enicolasgomez** [comment]
Attaching params compare tool

[https://app.zenhub.com/files/122103040/ba010e2a-5a1e-47f3-a15d-a9275616dad6/download](https://app.zenhub.com/files/122103040/ba010e2a-5a1e-47f3-a15d-a9275616dad6/download)

**Comment by pgleeson** [comment]
@enicolasgomez @ddelpiano I've tested this locally again with the latest NetPyNE-UI on the development branch. I tried loading this file: https://github.com/OpenSourceBrain/NetPyNEShowcase/blob/master/NetPyNE/UI/HHCellNetwork.txt_data.json (note https://github.com/MetaCell/NetPyNE-UI/issues/496 wasn't an issue on this branch), and it loaded fine, cell type & population tabs displayed fine, but pressing Create Network resulted in this:

<img width="1368" alt="Screenshot 2022-04-05 at 11 42 09" src="https://user-images.githubusercontent.com/1556687/161737029-f60cc202-1e74-4edb-ab02-1ff93f1af7a5.png">

**Comment by ddelpiano** [comment]
@enicolasgomez that utils module I think has been moved due to the migration to geppetto-meta, have you tried to search for convertToJS in the codebase? in case we need to adjust the import/require that call that method. Thx

**Comment by ddelpiano** [comment]
@salvadord @pgleeson I can confirm the issue it is triggered by the UI in the way the models are instantiated, but the issue itself seems a memory leak triggered from netpyne->neuron.

model used [here](https://raw.githubusercontent.com/OpenSourceBrain/NetPyNEShowcase/master/NetPyNE/UI/HHCellNetwork.txt_data.json)

The script Padraig is running does the following:
```
# From https://github.com/harshagurnani/GoC_Varied_Inputs/blob/ankur/Tests/single_cell/test_single_cell_netpyne_load.py

from pathlib import Path
from netpyne import sim
import json

json_file = Path('HHCellNetwork.txt_data.json')
with json_file.open(mode='r') as f:
    netpyne_info = json.load(f)

    netParams = netpyne_info['net']['params']
    simConfig = netpyne_info['simConfig']


    simConfig['saveJson'] = False # Prevent overwriting json gnerated by nml export
    simConfig['saveDat'] = True # Save data from this run
    print('> Creating, simulating, analyzing...')
    sim.createSimulateAnalyze(netParams=netParams, simConfig=simConfig,
                                  output=False)
    print('> Done...')
```

I tried to do something similar to what Padraig does but following the flow of what netpyne_geppetto calls, below the script:
```
from pathlib import Path
from netpyne import sim
import json

sim.initialize()
sim.loadAll('/Users/ddelpiano/git/netpyne-ui/workspace/padraig.json');
sim.gatherData()
netParams = sim.net.params
simConfig = sim.cfg
print('creating....')
sim.create(netParams, simConfig, output=True) # failed here
print('sim.create done')
sim.net.defineCellShapes()  # creates 3d pt for cells with stylized geometries
print('defineCellShapes done')
sim.gatherData(gatherLFP=False)
print('gatherData done')
sim.simulate()
```

The script above goes most of the time in segmentation fault, the culprits seems to be 2:
- we changed output=false in the sim.create call, this managed to let the instatiation work a couple of times (still not deterministic), even though I am not sure why this made a difference since createSimulateAnalyze wraps sim.create and set that to True no matter what.
- when I comment all the gatherData calls from the metacell script I can see that the model is instantiated consistently and it seems deterministic (it never failed), otherwise this fails.


Some issues/stacktrace reported:

1. when leaving the first gatherCall, usually I get the segFault but a couple of times I got this back
```
(netpyne) ddelpiano@192 workspace % python metacell_reload.py

Start time:  2022-04-22 13:00:11.147389
Loading file /Users/ddelpiano/git/netpyne-ui/workspace/padraig.json ... 
  Done; file loading time = 0.01 s
Loading simConfig...
Loading netParams...
Loading net...
  Created 2 cells
  Created 0 connections
  Created 0 stims
  Added NEURON objects to 2 cells
  Done; re-instantiate net time = 0.00 s
Loading simData...

Gathering data...
  Done; gather time = 0.00 s.

Analyzing...
  Cells: 2
  Connections: 0 (0.00 per cell)
creating....
python(89067,0x1086cbdc0) malloc: *** error for object 0x7f89f3523630: pointer being freed was not allocated
python(89067,0x1086cbdc0) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      python metacell_reload.py
```

2. When commenting the first gatherData but leaving the second I got the following:
```
(netpyne) ddelpiano@192 workspace % python metacell_reload.py

Start time:  2022-04-22 13:36:47.405631
Loading file /Users/ddelpiano/git/netpyne-ui/workspace/padraig.json ... 
  Done; file loading time = 0.02 s
Loading simConfig...
Loading netParams...
Loading net...
  Created 2 cells
  Created 0 connections
  Created 0 stims
  Added NEURON objects to 2 cells
  Done; re-instantiate net time = 0.00 s
Loading simData...
creating....

Start time:  2022-04-22 13:36:47.425962

Creating network of 1 cell populations on 1 hosts...
  Number of cells on node 0: 2 
  Done; cell creation time = 0.00 s.
Making connections...
  Number of connections on node 0: 0 
  Done; cell connection time = 0.00 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 4 traces of 3 types on node 0
sim.create done
defineCellShapes done

Gathering data...
  Done; gather time = 0.00 s.

Analyzing...
  Cells: 2
  Connections: 0 (0.00 per cell)
gatherData done
Traceback (most recent call last):
  File "/Users/ddelpiano/git/netpyne-ui/src/netpyne/netpyne/cell/compartCell.py", line 240, in initV
    for sec in list(self.secs.values()):
AttributeError: 'NoneType' object has no attribute 'values'
NEURON: Python Callback failed
 near line 0
 tstop=450.0
            ^
        finitialize(-65)
Traceback (most recent call last):
  File "metacell_reload.py", line 17, in <module>
    sim.simulate()
  File "/Users/ddelpiano/git/netpyne-ui/src/netpyne/netpyne/sim/wrappers.py", line 74, in simulate
    sim.runSim()
  File "/Users/ddelpiano/git/netpyne-ui/src/netpyne/netpyne/sim/run.py", line 161, in runSim
    h.finitialize(float(sim.cfg.hParams['v_init']))
RuntimeError: hoc error
```

**Comment by salvadord** [comment]
A couple of quick comments: 

- the sim.loadAll('/Users/ddelpiano/git/netpyne-ui/workspace/padraig.json'); call already instantiates the network so there is no need to create the net again, and this of course may trigger some errors.
 
- the "pointer being freed was not allocated" might be a separate issue related to the netpyne clearAll() func -- we might need to add some try/except blocks

I'm gonna try running the code

**Comment by salvadord** [comment]
Ok, so the following simpler code loads, instantiates and runs the network:

```
from netpyne import sim
sim.loadAll('HHCellNetwork.txt_data.json')
sim.simulate()
```

Since it loads the network instance from the json, and the json doesn't include the morphology (3d points) for each individual cell, it is not possible to plot the cell morphologies (and the UI will not be able to show them). 

However, there is an easy workaround by loading just the netParams and simConfig (ie. not instantiating the network by setting `instantiate=False`), and then instantiating the network from scratch based on netParams. This just requires cfg.saveCellSecs=True to ensure that the section 3d points will still be available after gathering data:

```
from netpyne import sim
sim.loadAll('HHCellNetwork.txt_data.json', instantiate=False)
sim.cfg.createCellSecs = True
sim.createSimulateAnalyze(sim.net.params, sim.cfg)
```

You can then check that the sec 3d points are there and can plot the morphologies:

```
In [8]: sim.net.cells[0].secs
Out[8]: {soma: {mechs: {pas: {e: -57.0, g: 0.00031}}, geom: {Ra: 34.56, cm: 1.6, pt3d: [[0.0, 0.0, 0.0, 17.841242], [0.0, 17.841242, 0.0, 17.841242]]}, vinit: -70.0, hObj: compartCell0.soma, topol: {}}, _repr_mimebundle_: {}}

sim.analysis.plotShape(preCell=['hhpop'], showFig=True)
``` 

<img width="621" alt="image" src="https://user-images.githubusercontent.com/8440562/164775114-37643f1c-2dd9-469f-8289-ef9775d1e23b.png">

So this should allow the UI to visualize the 3D structure of the loaded network.

**Comment by salvadord** [comment]
There are other ways of doing the same closer to the code that padraig was using, e.g.


```
from netpyne import sim
import json
from pathlib import Path

json_file = Path('HHCellNetwork.txt_data.json')
with json_file.open(mode='r') as f:
    netpyne_info = json.load(f) 
    netParams = netpyne_info['net']['params']
    simConfig = netpyne_info['simConfig']
    simConfig['saveCellSecs'] = True
    sim.createSimulateAnalyze(netParams=netParams, simConfig=simConfig,output=False)
```

```
In [6]: sim.net.cells[0].secs
Out[6]: {soma: {mechs: {pas: {e: -57.0, g: 0.00031}}, geom: {Ra: 34.56, cm: 1.6, pt3d: [[0.0, 0.0, 0.0, 17.841242], [0.0, 17.841242, 0.0, 17.841242]]}, vinit: -70.0, hObj: compartCell0.soma, topol: {}}, _repr_mimebundle_: {}}
```

**Comment by salvadord** [comment]
If we want to avoid recreating the network from netParams and just use the network instance info available in the json, we could potentially write a function to copy over the section information from netParams to net. Something like this:

```
from netpyne import sim
sim.loadAll('HHCellNetwork.txt_data.json')
sim.copySecInfoFromNetParamsToNet()


def copySecInfoFromNetParamsToNet():

  for cell in sim.net.cells:
    % check what cellParams it comes from
    % copy the info from netParams.cellParams[k].secs to sim.net.cells[i].secs

```

**Comment by pgleeson** [comment]
Thanks for looking into this in detail @ddelpiano @salvadord. It looks like there is a clearer way to get this sorted internally in NetPyNE UI (with sim.cfg.createCellSecs).  

@ddelpiano would you have time to try this out?

**Comment by ddelpiano** [comment]
@pgleeson not this week but I will give an update this coming Tuesday.

Thanks to both for the help and support!

**Comment by ddelpiano** [comment]
@salvadord I am putting this card on top of the backlog but right now we don't have enough time for this changes to be done.
The solution itself is simple, however this imply lots of testing with all the models supported, within this last sprint we don't have the necessary time to work on this.
Thanks.

**Comment by salvadord** [comment]
relevant code in netpyne_geppetto: https://github.com/MetaCell/NetPyNE-UI/blob/a35cf8c8a244d742fe7d4d33af8dde496976dc16/netpyne_ui/netpyne_geppetto.py#L410
