### ISSUE TITLE
Use checkAvailablePlots() (once available) to display enabled/disabled status for Plots

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/NetPyNE-UI#215]
netpyne will introduce a `checkAvailablePlots()` method to get a list of those plot types that have actual data.

We can use that in the UI to flag which plots can be viewed

**Comment by salvadord** [comment]
added function sim.analysis.checkAvailablePlots() 
returns a dictionary with keys indicate the name of the analysis function and values whether they are available or not (Boolean), e.g.

```
In [1]: sim.analysis.checkAvailablePlots()
Out[1]: 
{'plotConn': True,
 'plot2Dnet': True,
 'plotTraces': True,
 'plotRaster': True,
 'plotSpikeHist': True,
 'plotSpikeStats': True,
 'plotLFP': False,
 'granger': False,
 'plotRxDConcentration': False,
 'plotRatePSD': True}
```

Note that some plots require some configuration in sim.cfg.analysis for them to spit something meaningful (e.g. granger or plotRxDConcentration), but they are still work (are available) without that config.
