### ISSUE TITLE
Duplicated x86_64 after installation

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#216]
From #211 

> I've just reinstalled NetPyNE-UI and used a new conda env. Some things I noticed:

>After building (python utilities/install.py) I get a new x86_64 in the root dir. If I leave this there and start NP (./NetPyNE-UI) I get >the dreaded [I 11:32:34.920 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports error after it loads the >mods, and the app stalls at the splash screen. If I remove x86_64, it starts fine.

**Comment by lrebscher** [comment]
Having a x86_64 folder at root level after running `utilities/install.py` is intended, it contains the compiled mod files.
I cannot reproduce the error, tried it with my local dev setup and in docker, need more information

**Comment by pgleeson** [comment]
It may well be to do with having multiple versions of Neuron on my machine, one default and NP installs its own copy. If a different version of Neuron is used to build and then load the files, it will probably fail. I'll check into it more.
