### ISSUE TITLE
Merge cns2020 back to master

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#217]
From #211 

>The branch of netpyne_workspace used is master, even though there are lots of changes (fixing some issues) on the cns2020 >branch: Neurosim-lab/netpyne_workspace@master...cns2020. Merge to master?

**Comment by salvadord** [comment]
I merged the "nov2020" branch (which actually had the latest version) into master -- let me know if that works, or if there are any issues

**Comment by filippomc** [comment]
Tested the latest master, looks good. Using it on netpyne-ui new deployments
