### ISSUE TITLE
Experiment manager implementation

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#229]
mockups:
https://www.figma.com/proto/E2W6Gh7yjaLaY3lo9PCm40/OSB2%2FNetPyNE%2FNWBE?node-id=0%3A1

![Screenshot 2021-03-17 at 10.55.44.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/96507ff3-a621-4091-8166-22ad91c9935b)![Screenshot 2021-03-17 at 10.55.50.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/d9ff9dce-982b-467c-8c17-a8d143a77684)

The focus of this card is the implementation of the experiment manager component within the flexlayout implementation, few notes:
- the component will be controlled by the left side bar
- the component will be available in both edit and explore views.
- the focus of this card is the scaffolding implementation of the component as displayed in the mockups, there will a follow up card to plug all the actions driven by the buttons on the right visible in the mockups.
- important note, refere to the mockups on figma and not the screenshot attached, these have been made before the latest changes paul worked on so there might be some small difference from screenshots and mockups.

Feel free to remove you from this card once done
Thanks to both!

**Comment by lrebscher** [comment]
I added a component `Experiments.js` that loads the dummy experiments from the backend.

@vidhya-metacell  you don't have to do any direct calls to the backend, I prepared some Redux that you can call to trigger button actions, they are just dummy actions though :) , but as Dario wrote in the description: the action handling will come in a later issue.

The only thing that's not contained in the Experiment model yet, is the model specification trial (the one separate from the exploration trials), just use dummy data for that. Besides that, the fetched experiments should contain all information (and some additional one not relevant to this view).

**Comment by lrebscher** [comment]
@vidhya-metacell  some additional information on the Experiment state:

For now, we can have the following states: DESIGN, SIMULATING, INSTANTIATING, SIMULATED, INSTANTIATED, ERROR
SIMULATING and INSTANTIATING both show the spinner icon

@ddelpiano do we have a design for the ERROR state?

We also have to specify which actions should be enabled/disabled depending on the state. E.g. the "reload" button doesn't really make sense at an experiment in design. But maybe not scope of this issue
