### ISSUE TITLE
Autocomplete Tree component implementation

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#235]
![Screenshot 2021-03-26 at 09.48.38.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/a65c8366-9d41-4880-971a-04ccee93b076)
![Screenshot 2021-03-26 at 09.48.46.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/6d92bdb2-be4b-430a-8966-76bcdb1300f4)

This component is part of the experiment creator/editor.
The entry point is the input text used to give the parameter path.

To be given for the implementation (cc @lrebscher ):
- how to get the json to be used for the tree representation.
- how to determine if the parameter can be selected (if the key is not an obj or list?).

**Comment by ddelpiano** [comment]
@vidhya-metacell this is the component already present in geppetto-client that I think might be useful for the implementation of this.
https://github.com/openworm/geppetto-client/tree/development/geppetto-ui/src/tree-viewer

**Comment by lrebscher** [comment]
@vidhya-metacell  use the `viewParameters` function in `EditExperiment.js` to get a JSON version of the current netParams dictionary.
