### ISSUE TITLE
Lazy loading for plots

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#238]
extracted from https://docs.google.com/document/d/1uyY4-fuECBuUxJ_zXaHVcGwLEzqfS7mgOxUimu_q2ZA/edit#

@filippomc @lrebscher guys could you put some details related to the implementation and estimate on this card please? Thx

**Comment by lrebscher** [comment]
Closing this one, already implemented as mentioned in the sprint meeting
