### ISSUE TITLE
Netpyne should offer a method to generate trials (parameter combinations) based on given parameters

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/NetPyNE-UI#240]
Currently, the batch parameter combinations are generated within the batch module when a user runs the batch.

However, in Netpyne-UI we have to list the trials before we instantiate/simulate an Experiment.

Therefore, netpyne should offer a method that takes the parameter configuration as input and returns the resulting parameter combinations.

It would be ideal if we could simply link a parameter combination to its output file on disk by using this method or additional information.

Filename pattern that we have to parse in Netpyne-UI: https://github.com/Neurosim-lab/netpyne/blob/f570da999a8445219bee8dcefec6744637ec464f/netpyne/batch/grid.py#L199

For this, we need a list of the parameter combination indices together with their values.

`params` argument as method input:
```python
{
 {
  "label": "labelA",
  "values": [1,2],
  "group": False
 },
 {
  "label": "labelB",
  "values": [1, 2, 3],
  "group": False
  }
}
```

expected output:
```python
{
 "indices": [(0,0),(0,1),(0,2),(1,0),(1,1),(1,2)],
 "values": [(1,1),(1,2), ...],
 "labels": ["labelA", "labelB"]
}
```

**Comment by salvadord** [comment]
pushed changes to the 'mapping' branch: https://github.com/Neurosim-lab/netpyne/tree/mapping (https://github.com/Neurosim-lab/netpyne/commit/94c89917c04b4082e0a12a724a6af52281d338e1)

the method `batch.getParamCombinations()` now returns the structure you requested above; I also included a dict entry `filenames` with the name of the output filenames on disk, including relative folder path. I'm not sure if this is redundant as it can be obtained from the indices. Anyway let me know what you think and if you want me to add/remove anything.

**Comment by lrebscher** [comment]
thx! Tested it in the Netpyne-UI experiments flow & works as expected! 
The folder path won't be necessary but the filenames might come in handy, we could leave it as it is and check in again once the feature is completed
