### ISSUE TITLE
Support JSON input for netpyne.batch.Batch

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#242]

**Comment by salvadord** [comment]
@lrebscher I implemented a new approach based on our discussions. Here's the summary (can discuss in meeting tomorrow):

- NetParams includes new attribute mapping dict, with keys = corresponding cfg variable and values= hierarchical structure within netParams, e.g. netParams.mapping['AMPAgmax'] = ['synMechParams', 'AMPA', 'gmax']
- mapping values get set during sim.initialize()
- can pass a netParams object with mapping directly to batch()
- netParams gets saved as json in target batch folder
- netParams will be read from json for each sim through command line arguments, and the mapping will get set up during sim.initialize()
- cfg can still be provided as object, and will be saved as json in target batch folder 

- example (run batch.py): https://github.com/Neurosim-lab/netpyne/tree/mapping/examples/batchCellMapping

- main changes to netpyne code:
https://github.com/Neurosim-lab/netpyne/blob/mapping/netpyne/batch/batch.py#L181
https://github.com/Neurosim-lab/netpyne/blob/mapping/netpyne/sim/setup.py#L157
https://github.com/Neurosim-lab/netpyne/blob/mapping/netpyne/specs/netParams.py#L602

**Comment by lrebscher** [comment]
That is what we needed, thx! :)
