### ISSUE TITLE
Restructure 'cellModel' so part of cellParams not popParams

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#243]

**Comment by salvadord** [comment]
Made changes so user can specify 'cellModel' and point neuron params in netParams.cellParams (not only in netParams.popParams). This makes the format closer to NeuroML and removes the need to use 'cellModel' in popParams, which could be confusing. It also allows for more consistency when implementing the GUI. 

I updated the doc/source/code/tut_artif.py and examples/HybridTut examples to illustrate the changes.

Here's the PR: https://github.com/Neurosim-lab/netpyne/pull/598
