### ISSUE TITLE
Connectivity rule - change data type for weight

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#247]
connParams weight is a string, not float, still works because interprets as string-based func, but should be a float if just a number.

to do:
- put a mask on the frontend to set only numbers
- type check on the backend ?

**Comment by ddelpiano** [comment]
@lrebscher if it's easy enough I would include this in the next release, your and @filippomc 's call here. Thx

**Comment by lrebscher** [comment]
still allow string expressions, detect if number & convert to float
