### ISSUE TITLE
Bokeh plots png save

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#248]
![Screenshot 2021-03-26 at 12.51.15.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/be9e49e4-93bb-4bc0-8b09-ad6063652a6e)
![bokeh_plot (1).png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/4b89c73c-cd2f-4cdb-9485-cd9cd66138df)

- plot image right now is clipped and not displaying the entire plot, example attached

**Comment by lrebscher** [comment]
@salvadord  the plot output is HTML generated by Bokeh that was created by `netpyne.analysis.iplot2Dnet` method.
We pass this output to the frontend and the save functionality is part of Bokeh, so I don't think that it's a Netpyne-UI problem.

I extended the `gui_tut1.py` by the following lines and could reproduce the bug without Netpyne-UI:
```Python
from netpyne import analysis
from netpyne import sim

sim.createSimulateAnalyze(netParams, simConfig)

html, data = analysis.iplot2Dnet(showFig=False)

with open("plot.html", "w") as f:
    f.write(html)
```

**Comment by salvadord** [comment]
@joewgraham I think you implemented this one... please can you have a look at this? thx

**Comment by joewgraham** [comment]
I was getting a crash generating the iplot and had to update Bokeh's active_drag and active_scroll options from None to "auto".  I don't get clipped plots when I save as png.  Could someone please see if they can still replicate this error using the latest dev branch?

**Comment by lrebscher** [comment]
@joewgraham thx for the update! I tested it but it I still got the error, this gave me the idea that it might be bokeh itself.
We used bokeh version 2.1.1 and after updating to bokeh 2.3.1 the issue was resolved
