### ISSUE TITLE
Json import - Fix sim.loadAll

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#249]
Following up what discussed in the previous sprint calls, this is an extract from the robustness improvements analysis done by Filippo.

Trigger: import hnn json file

Possible causes:
The data structure after the json loading is different from what we get from a plain instantiation: we get pure dictionaries rather than custom netpyne structures like PopParams etc (which are basically ordered dictionaries but with some api too)

To do:
Fix the sim.loadAll - loadNet to convert the netParams object sections to the netpyne object wrappers

**Comment by pgleeson** [comment]
@ddelpiano @salvadord This is clearly related to the issues we've been having getting getting netpyne json originating from neuroml to load into netpyne-ui. 

My experience though is that is not a given that any python/json which was exported from netpyne(ui) can be loaded back into netpyne-ui without hitch (sometimes it loads, sometimes the cells don't display in 3D, sometimes the sim doesn't run...). And then there's finding and compiling/linking the mod files...

I'd say HNN isn't the best place to start to iron out all these issues, simpler examples might highlight some problems. I've tried to make some simple scripts for testing json/python saving/reloading here: https://github.com/OpenSourceBrain/NetPyNEShowcase/tree/master/NetPyNE/UI which might be useful for the process.

**Comment by salvadord** [comment]
I modified the netParams class so when passing a dict to the constructor (eg. when loading from file), the components of netParams (cellParams, connParams, etc) are stored using the correct classes. I tested on padraig's example above and the netpyne_workspace hnn.

Github changeset: https://github.com/Neurosim-lab/netpyne/commit/b56cdcdb987afbfd68d4c70674513badcbbc6894 

Let me know if it helps to fix some of the problems loading json in the GUI.

**Comment by filippomc** [comment]
Hey @salvadord, getting this error when importing hnn.json with latest development:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/NetPyNE-UI/netpyne_ui/netpyne_geppetto.py in loadModel(self=<netpyne_ui.netpyne_geppetto.NetPyNEGeppetto object>, args={'areModFieldsRequired': False, 'compileMod': False, 'exploreOnlyDirs': False, 'explorerDialogOpen': False, 'explorerParameter': 'jsonModelFolder', 'freezeInstance': True, 'freezeSimulation': True, 'jsonModelFolder': '/home/user/NetPyNE-UI/netpyne_workspace/hnn.json', 'jsonPath': '/home/user/NetPyNE-UI/netpyne_workspace/', 'loadNet': True, ...})
    226                             sim.loadSimData(args['jsonModelFolder'])
    227 
--> 228                     self.geppetto_model = self.model_interpreter.getGeppettoModel(sim)
        self.geppetto_model = <pygeppetto.model.model.GeppettoModel object at 0x7f609d3fcd10>
        self.model_interpreter.getGeppettoModel = <bound method NetPyNEModelInterpreter.getGeppettoModel of <netpyne_ui.netpyne_model_interpreter.NetPyNEModelInterpreter object at 0x7f60f08f0290>>
        global sim = <module 'netpyne.sim' from '/home/user/NetPyNE-UI/src/netpyne/netpyne/sim/__init__.py'>
    229                     return json.loads(GeppettoModelSerializer.serialize(self.geppetto_model))
    230                 else:

~/NetPyNE-UI/netpyne_ui/netpyne_model_interpreter.py in getGeppettoModel(self=<netpyne_ui.netpyne_model_interpreter.NetPyNEModelInterpreter object>, netpyne_model=<module 'netpyne.sim' from '/home/user/NetPyNE-UI/src/netpyne/netpyne/sim/__init__.py'>)
     25         geppetto_model.libraries.append(netpyne_geppetto_library)
     26 
---> 27         self.extractPopulations(netpyne_model, netpyne_geppetto_library, geppetto_model)
        self.extractPopulations = <bound method NetPyNEModelInterpreter.extractPopulations of <netpyne_ui.netpyne_model_interpreter.NetPyNEModelInterpreter object at 0x7f60f08f0290>>
        netpyne_model = <module 'netpyne.sim' from '/home/user/NetPyNE-UI/src/netpyne/netpyne/sim/__init__.py'>
        netpyne_geppetto_library = <pygeppetto.model.model.GeppettoLibrary object at 0x7f60bcff8650>
        geppetto_model = <pygeppetto.model.model.GeppettoModel object at 0x7f609bde7650>
     28         self.extractInstances(netpyne_model, netpyne_geppetto_library, geppetto_model)
     29 

~/NetPyNE-UI/netpyne_ui/netpyne_model_interpreter.py in extractPopulations(self=<netpyne_ui.netpyne_model_interpreter.NetPyNEModelInterpreter object>, netpyne_model=<module 'netpyne.sim' from '/home/user/NetPyNE-UI/src/netpyne/netpyne/sim/__init__.py'>, netpyne_geppetto_library=<pygeppetto.model.model.GeppettoLibrary object>, geppetto_model=<pygeppetto.model.model.GeppettoModel object>)
     37         # Create intermediate population structure for easy access (by key)
     38         populations = {}
---> 39         for index, cell in enumerate(netpyne_model.net.allCells):
        index = undefined
        cell = undefined
        global enumerate = undefined
        netpyne_model.net.allCells = undefined
     40             # This will be only executed the first time for each population
     41             if cell['tags']['pop'] not in populations:

AttributeError: 'Network' object has no attribute 'allCells'
```

After that error I can instantiate the network in the ui anyway, not sure what we are missing there.
Loading from python works fine with the same version.

**Comment by salvadord** [comment]
not sure why netpyne_ui would be checking net.allCells after importing the json? the json may only contain the netParams (no net) so you wouldn't expect to have net.allCells.
