### ISSUE TITLE
Kernel crash and restart after simulating first Tutorial 1 and then Tutorial 2

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/NetPyNE-UI#263]
Specific situation for a problem described in Point 1 in #225

**Comment by lrebscher** [comment]
First step is to ensure that we call sim.clearAll() before we import a Tutorial

**Comment by lrebscher** [comment]
calling `sim.clearAll` before simulating fails since some attributes are not necessarily present

currently, there is a custom `clearSim()` method in `netpyne_geppetto.py`which is used instead and only called once the user deletes a model.

`clearSim` expects the presence of certain attributes as well. I fixed this with presence checks but the kernel still crashes and restarts without error logs

@salvadord  At this point, I think it makes sense to investigate this issue outside of Netpyne-UI and check why the simulations fail internally in netpyne and find out what has to be cleaned up in netpyne so that simulating different models doesn't require a kernel restart

**Comment by joewgraham** [comment]
I was able to replicate the kernel crash in iPython.  I modified sim.clearAll such that it works even before simulations have been run.  Now when I run tut1, do sim.clearAll, and run tut2 it completes successfully.

https://github.com/Neurosim-lab/netpyne/commit/cc8a0bc140daace2c8db8f7fb097cd763175d5ed

**Comment by lrebscher** [comment]
@joewgraham  that are really good news!

tried to replicate that in Netpyne-UI but the kernel still crashes 

I also receive an attribute error when calling sim.clearAll, "pc" attribute is not present, even when I already simulated a model before (Tut 1). I added a check for pc in the method so that I can test it, but the kernel still crashes

I'm wondering why "pc" is not present in my case, do you know why? What is "pc" actually and why should it be present?

Maybe that's the important difference between your script in iPython and Netpyne-UI

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/git/NetPyNE-UI/netpyne_ui/netpyne_geppetto.py in simulateNetPyNEModelInGeppetto(self=<netpyne_ui.netpyne_geppetto.NetPyNEGeppetto object>, args={'parallelSimulation': False})
    130                 else:
    131                     # single cpu computation
--> 132                     sim.clearAll()
        global sim.clearAll = <function clearAll at 0x1361de710>
    133                     logging.info("Starting simulation")
    134                     netpyne_model = self.instantiateNetPyNEModel()

~/git/NetPyNE-UI/src/netpyne/netpyne/sim/utils.py in clearAll()
    844     # clean up
    845 #    if hasattr(sim, "pc"):
--> 846     sim.pc.barrier()
        sim.pc.barrier = undefined
    847     sim.pc.gid_clear()                    # clear previous gid settings
    848 

AttributeError: module 'netpyne.sim' has no attribute 'pc'
```

**Comment by salvadord** [comment]
that's great joe!

**Comment by lrebscher** [comment]
@salvadord when we import a Tutorial (from Python) and simulate, `sim.initialize()` is never explicitly called in Netpyne-UI, but we call it when importing a JSON model

I added it to the Python import as well and with some other changes to the code it now works (49707af), so thx for that hint!

Import Tut 1 -> Simulate -> Import Tut 2 -> Simulate doesn't require kernel restart with these changes

It's still WIP, I need to understand when each of the lifecycle methods should be called in the Netpyne-UI flow. As part of these changes, we always instantiate the network when a user clicks on "Simulate" to ensure that the instance matches with netParams and simConfig. Before, the previous instance was reused but that causes issues in this particular flow
