### ISSUE TITLE
Evaluate current state of NEURON cleanup issue

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/NetPyNE-UI#267]
Running different simulations of different models in the same Python kernel leads in some cases to a Kernel crash.

We assume that NEURON doesn't clean up properly and some left over objects cause issues

Task is to test this assumption with the most recent NEURON version and to search for any information that might be helpful

**Comment by salvadord** [comment]
salvadord  11:15 AM
btw, in a related issue, is there a systematic way to remove all NEURON objs from memory after creating a network model? i.e. clearing everything so it’s equivalent to starting from scratch (new python kernel)
11:17
we’ve tried removing all python objs that point to or contain NEURON objs (including nested structures) and then calling garbage collect … but that doesn’t work for all cases


Pramod Kumbhar  12:28 PM
By the way - we should find out whats causing this error. And clearing everything so it's equivalent to starting from scratch (new python kernel) is also something we constantly come across in BBP use cases. So something to be looked at...

Michael Hines  4:45 PM
There is always a quit() and start again from bash:)  But, the most common desire is to destroy a model and start again. That is easiest when the model is an instance of a class. For parallel, pc.gid_clear() is your friend and that should be done first, then NetCons, then cells.
