### ISSUE TITLE
Clean up RXD component leftovers from simulations

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/NetPyNE-UI#310]
Tut 3b -> T3c breaks while Tut 3a -> Tut3b works although Tut 3a -> Tut (2,4) breaks

sth that is not cleaned up in Tut 3a breaks subsequent tutorials

The goal is that users can import a JSON/Python model without having leftovers from previous models cause problems.

**Comment by salvadord** [comment]
Checked with RxD guys and will implement their suggestions below:

salvadord  7:24 PM
any special advice on how to completely clear rxd objects from memory so can run a new fresh simulation from scratch within same python kernel? is it just gid_clear and removing all python pointers to the rxd objects?
New

adamnewton  7:36 PM
That should work, if not this is the script we use to reset rxd stuff after running a CI test; https://github.com/neuronsimulator/nrn/blob/7b73c7025792e22aefdac5a9244c1561acef48fb/test/rxd/conftest.py#L57-L76 (edited) 

conftest.py
    for r in rxd.rxd._all_reactions[:]:
        if r():
            rxd.rxd._unregister_reaction(r)

    for s in rxd.species._all_species:
        if s():
            s().__del__()
    rxd.region._all_regions = []
    rxd.region._region_count = 0
    rxd.region._c_region_lookup = None
    rxd.species._species_counts = 0
    rxd.section1d._purge_cptrs()
    rxd.initializer.has_initialized = False
    rxd.rxd.free_conc_ptrs()
    rxd.rxd.free_curr_ptrs()
    rxd.rxd.rxd_include_node_flux1D(0, None, None, None)
    rxd.species._has_1d = False
    rxd.species._has_3d = False
    rxd.rxd._zero_volume_indices = numpy.ndarray(0, dtype=numpy.int_)
    rxd.set_solve_type(dimension=1)
