### ISSUE TITLE
Remove Model > Explore View options & change simulation/network buttons

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/NetPyNE-UI#347]
The menu option `Explore view options` in the Model menu should be removed.

The functionality enabled to switch the top right `CREATE NETWORK` button to `CREATE AND SIMULATE`.

We want to keep this option by adding a third button to the top right corner or using some other UI element to easily switch between create and simulate and only create.

**Comment by lrebscher** [comment]
E.g. we could use a split button:

<img width="293" alt="Bildschirmfoto 2021-06-28 um 12 03 30" src="https://user-images.githubusercontent.com/7281685/123618941-f6fc4d00-d808-11eb-8533-12c3c3598348.png">

**Comment by lrebscher** [comment]
**In Edit mode**
- Create network button with two alternatives
  - create and simulate
  - simulate

**in Explore mode**
* Simulate button
* Back to edit

**Model Menu**
* Add "Create and Simulate"
* Remove "Explore view options"

**Term**
"instantiate" vs "create network"

**Comment by filippomc** [comment]
I personally like more "create network", it looks clearer to the user, unless the context makes the meaning of "instantiate" clear.

Another point may be about having in the edit mode a way to go back to the network view 
once the network is istantiated.
