### ISSUE TITLE
Sort by Name in ExperimentsView not return expected order

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/NetPyNE-UI#368]
![Bildschirmfoto 2021-07-26 um 20.06.08.png](https://images.zenhubusercontent.com/600fdb37a2c5e223bc039639/fbf95d25-ddc4-49ad-a747-c52011ca49f5)

**Comment by lrebscher** [comment]
`stableSort` in `utils.js` has to be modified to work for Trial name with format `Trial <number>`

Or, we just use numbers instead of "Trial 1"

**Comment by ddelpiano** [comment]
@enicolasgomez could you give us an update on this?
I am removing @vidhya-metacell since as Filippo suggested this should be changed directly on the backend, but if there is any change required on the frontend feel free to leave a comment and re-add @vidhya-metacell to the card.

**Comment by ddelpiano** [comment]
done as part of meta-migration
