### ISSUE TITLE
MPI - cannot specify as many cores as the machine has

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/NetPyNE-UI#372]
mpi - not enough slots available to satisfy 9 slots, although my machine has 16 cores

**Comment by lrebscher** [comment]
https://github.com/open-mpi/ompi/issues/6020

**Comment by salvadord** [comment]
@lrebscher shouldn't the "--use-hwthread-cpus" go before the "nrniv" commands, since it's an optional argument of "mpiexec"?

**Comment by lrebscher** [comment]
yes you're right & I just noticed that you don't have to edit anything in netpyne for now.

That part in grid.py is connected to `hpc_slurm` method, for `mpi_bulletin` we handle this in netpyne-ui

So you could apply this change if this makes sense in the slurm context, but for now we're good to go with the changes made in Netpyne-UI :)
