### ISSUE TITLE
UI should default to using structural/3D info from cellParams (template) when not found in cells (instance)

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/NetPyNE-UI#374]
Error found when importing JSON representation of networks. 
The info on cell structure is present in the cell params entry as a template for all cells in that population, but each of the entries under net/cells/0 etc. normally has a repeat of this. It can be missing though ([file](https://github.com/OpenSourceBrain/NetPyNEShowcase/blob/ff1de5a25f12d44e4fdf3ba393117809d643e6d0/NetPyNE/UI/HHworks2.json#L7)):
<img width="317" alt="Screenshot 2021-07-28 at 17 08 15" src="https://user-images.githubusercontent.com/1556687/127357676-90c47727-f5a2-46eb-b92f-d3474b16d7b3.png">

I get an error when I load this in the UI. The UI should fall back to using the info in the cellParams template when it is missing in the instance

<img width="1008" alt="Screenshot 2021-07-28 at 17 10 41" src="https://user-images.githubusercontent.com/1556687/127358036-19edefab-db71-4ea2-b707-75c467c56c91.png">

**Comment by Muhaddatha** [comment]
Please ignore my commit above from July 29th. I made a mistake with the issue number in the commit message. The commit is related to issue #347 and not #374.

**Comment by pgleeson** [comment]
I think this is fixed now with the nml related updates
