### ISSUE TITLE
UI should automatically convert dicts of netParams/simConfig to their class equivalent

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/NetPyNE-UI#375]
When I try to import python files (which have variables netParams/simConfig) in the UI I get an error if the netParams/simConfig variables are dicts (e.g. loaded from a json file, as here: https://github.com/OpenSourceBrain/NetPyNEShowcase/blob/ff1de5a25f12d44e4fdf3ba393117809d643e6d0/NetPyNE/UI/reload2.py)

This seems to be related to the UI keeping the netParams etc as a dict and trying to use it as a NetParams class. 

<img width="976" alt="Screenshot 2021-07-28 at 17 14 31" src="https://user-images.githubusercontent.com/1556687/127358712-1337ae7f-4fcb-46c6-9b16-28950acf789b.png">

The best solution would be for the UI to check whether it's a dict, try to convert it to NetParams() etc., then continue.

**Comment by lrebscher** [comment]
Before we set `self.netParams` in the `importModel` method we should check whether it's a `netpyne.spec.NetParams`object or a `dict`. In the latter case we will transform it to `NetParams`.

Same procedure for `simConfig`

At the end, the `importModel` method should work with python files that use either plain dicts or the netpyne types to declare netParams and simConfig.

Above, Padraig provided a JSON that can be used to test the dict case, for the other cases we can use e.g. `gui_tut1.py` in the workspace
