### ISSUE TITLE
pip installation can't find netpyne==0.7.8.1

### ISSUE THREAD

**Issue by joewgraham** [MetaCell/NetPyNE-UI#38]
I'm trying to install on an Ubuntu VM.  Output:

(ocnc2018) ocnc@ocnc-VirtualBox:$ pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple netpyne_ui
Looking in indexes: https://test.pypi.org/simple/, https://pypi.org/simple
Collecting netpyne_ui
  Downloading https://test-files.pythonhosted.org/packages/40/5d/9737f6f0beb0206720f4bd67a01c01ef2600218bb12b6da6b8cac968f617/netpyne_ui-0.3.tar.gz
Collecting jupyter_geppetto==0.4.1 (from netpyne_ui)
  Downloading https://test-files.pythonhosted.org/packages/3c/1a/a09d176bb772136211fc3afe69b39542924a1ec7d88b1ada1eebf5d23b0f/jupyter_geppetto-0.4.1.tar.gz (31.9MB)
    100% |████████████████████████████████| 31.9MB 1.7MB/s 
Collecting netpyne==0.7.8.1 (from netpyne_ui)
  Could not find a version that satisfies the requirement netpyne==0.7.8.1 (from netpyne_ui) (from versions: 0.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6.4)
No matching distribution found for netpyne==0.7.8.1 (from netpyne_ui)
(ocnc2018) ocnc@ocnc-VirtualBox:$

**Comment by tarelli** [comment]
@joewgraham 0.7.8.1 is there https://test.pypi.org/project/netpyne/ we just tried it ourselves also within a ubuntu vm (which we are uploading as I type), worth it trying again?

**Comment by joewgraham** [comment]
I just restarted and tried it again and got the same error.

**Comment by tarelli** [comment]
@joewgraham what happens if you run `pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple netpyne`?

**Comment by joewgraham** [comment]
That gives a new error:

(ocnc2018) ocnc@ocnc-VirtualBox:~$ pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple netpyne
Looking in indexes: https://test.pypi.org/simple/, https://pypi.org/simple
Collecting netpyne
  Downloading https://files.pythonhosted.org/packages/24/11/af39f303131a549287469dc49057bf30f87af21a52586f085c94e96a10d1/netpyne-0.6.4.tar.gz (85kB)
    100% |████████████████████████████████| 92kB 1.1MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0k7l20q7/netpyne/setup.py", line 12, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/home/ocnc/anaconda3/envs/ocnc2018/lib/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-0k7l20q7/netpyne/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-0k7l20q7/netpyne/
(ocnc2018) ocnc@ocnc-VirtualBox:~$

**Comment by adrianq** [comment]
@joewgraham It looks to me you are trying to install it for python 3. NetPyNE-UI and its dependencies only work for python 2. This is why pip keeps telling you that cannot find the package. Try to use a virtual environment if you have python 3 in your system.

**Comment by joewgraham** [comment]
Thanks Adrian!
