### ISSUE TITLE
Don't display ErrorDialog when getExperiments call fails in background

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/NetPyNE-UI#381]
the `handle_output` function of GeppettoJupyterUtils  will trigger for each python call that failed a `GEPPETTO.Events.Error_while_exec_python_command` which then is used to open the `ErrorDialog` in `NetPyNe.js`.

However, for experiments we use polling to update the experiments every x seconds.

If the backend moves to a faulty state (e.g. kernel crash), it will open every x second an Error dialog making the UI unusable.

To solve it, (1) the `handleOutput` method should make it either optional to trigger the Error event, so that we can use sth like `evalPythonMessage(command, parameters, silent=True)` or (2) the error event is parsed and in certain cases we won't show the ErrorDialog.

**Comment by enicolasgomez** [comment]
@ddelpiano 1) migth work, ideally I would do 3) in which I would tag any `execute_result` call with a GUID which would be taken by the JS layer and maintain a error output list adding the element in case it's been errored out, if the GUID is already there it won't error out again.

This GUID would also work as a flag to tag the `execute_result` call to adopt this behavior only in case the value is present.

**Comment by enicolasgomez** [comment]
also seeing this old ticket #383 I think what's missing is an orchestrator for the experiments that would error out once, if the experiment fails to execute in any circunstance.
