### ISSUE TITLE
Batch error detection is not reliable

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/NetPyNE-UI#383]
**Description**

An experiment is marked as ERROR if the master process detects that data files are missing.

The master process runs this detection once all workers finished.
This happens after `grid.py` waited until `pc.working` evaluated to False.

However, a data file seems to be actually written some time after the simulation finished. At the moment, this makes it impossible to know if a simulation failed or not. Depending on the underlying filesystem it can take more than 10 seconds until data files show up (e.g. on deployed instance in Google cloud).

Currently, Experiments get often flagged as ERROR although data files will show up after some time.

**Proposed solution**

In order for the detection to work, a netpyne simulation needs to wait until its _data file exists before exiting.

**Comment by lrebscher** [comment]
okay I think my sentence wasn't precise enough: my idea was that in `save.py::saveJSON` netpyne would wait until `os.path.exists(filename)` and then continue, that way it could be ensured that the master process also finds this file existing. 

At least that's my first idea without having invested more time in studying the problem

**Comment by salvadord** [comment]
Lucas, I added the code to save.py::saveJSON - https://github.com/Neurosim-lab/netpyne/commit/07973876fa995ccfb8338bff3a3bd0a89ac3f7f1

I made it optional, and also included a timeout, so that it doesn't loop forever if the file is not created. I pushed these changes to the mapping branch so we can try them out first.

**Comment by lrebscher** [comment]
@salvadord  just tested in netpyne-ui, small bug:`checkFile` should be `checkFileTimeout`
<img width="878" alt="Bildschirmfoto 2021-08-11 um 10 44 45" src="https://user-images.githubusercontent.com/7281685/128998672-d0c4168f-d510-47ca-b96c-ac9987bcbbf8.png">

**Comment by salvadord** [comment]
whoops, sorry, fixed here: https://github.com/Neurosim-lab/netpyne/commit/4394b3293c0a63817018272a92fc8228a403f351
