### ISSUE TITLE
import model file browser empty

### ISSUE THREAD

**Issue by salvadord** [MetaCell/NetPyNE-UI#39]
![image](https://user-images.githubusercontent.com/8440562/42128271-b2b978a8-7c75-11e8-9a94-0ffb34949d39.png)

using docker version on Mac OS: 
docker run -it -v /u/salvadord/Documents/ISB/Models/netpyne_tutorial_CNS18:/home/jovyan/netpyne_workspace -p 8888:8888 metacell/netpyne-ui

**Comment by salvadord** [comment]
same for import cell template

**Comment by tarelli** [comment]
@salvadord What version of Mac OS/browser?
<img width="1239" alt="screen shot 2018-06-30 at 20 12 58" src="https://user-images.githubusercontent.com/81127/42128390-14467608-7ca2-11e8-943a-46307083e484.png">

**Comment by tarelli** [comment]
Also seems to be missing some text (Select a file), did you clear the cache? Is the docker the latest version?

**Comment by salvadord** [comment]
OS 10.12.6
Chrome Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by rodriguez-facundo** [comment]
I can't reproduce this error. It seems to be working fine for me.

But take into consideration that you need to update all the repos for this to work, not only NetPyNE-UI and netpyne-geppetto, but also **_org.geppetto.frontend_**

**Comment by tarelli** [comment]
This was due to not updating the docker image, works now.
