### ISSUE TITLE
Switching between Edit > Explore freezes UI for many seconds in case of complex 3D Scene

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/NetPyNE-UI#394]
**Reproduction**

* Import Tutorial 2
* Create Network -> moves to explore view
* Go back to Edit
* Use `Model > Explore` in menu to switch to Explore view

**Description**
When we use the menu no instantiation is happening, it just re-adds the network widgets to the layout by triggering `SHOW_NETWORK` action.

But the 3DCanvas takes quite some time to load, blocking the UI for many seconds.

We should display a loading spinner during that time.
However, this loading spinner doesn't show up when triggering it in the middleware that handles `SHOW_NETWORK` action.

Presumably, this is due to the fact that two other `SET_LAYOUT` actions are fired before this action. These actions block the UI, so that the loading spinner doesn't show up.

**Comment by enicolasgomez** [comment]
@ddelpiano this one is no longer reproduceable on geppetto-meta branch
