### ISSUE TITLE
Add sentry to Netpyne

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#422]
When compiled in production mode we should connect the deployment to our internal sentry so that we can use that to collect issues during users usage.

**Comment by enicolasgomez** [comment]
Done and added some intentional failing cases to test logging at the backend

![Screen Shot 2021-11-26 at 12.05.28 PM.png](https://images.zenhubusercontent.com/610183f51ec1245011ca9923/ac78eab1-1330-48af-9fd1-2910e2051f26)

**Comment by enicolasgomez** [comment]
@ddelpiano added sentry loging to python layer as requested
