### ISSUE TITLE
remove console.log flooding since removal of the geppetto command controller

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#430]
refactor the console.log left in the code to replace the absence of the old command controller.
We can set a global env value to display this only in development but suppress these messages if we are doing a prod build.

**Comment by enicolasgomez** [comment]
@ddelpiano the console log flooding comes from geppetto actually:
https://github.com/MetaCell/geppetto-meta/blob/979edf300e4de41db432a38dae13f3ca95af90e5/geppetto.js/geppetto-client/src/GEPPETTO.js#L72

which are catched by the sentry agent as it's configured to report warnings.

Should we change sentry to be les verbose in dev?
Or do we want geppetto-meta to handle this?

**Comment by ddelpiano** [comment]
@enicolasgomez better to address both imo.
