### ISSUE TITLE
Load the same tutorial twice keeps the previous state of that model

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#437]
load tutorial 1
cancel population
reload tutorial 1
the population does not appear

**Comment by enicolasgomez** [comment]
#489 blocking as I can't successfully cancel de population

**Comment by ddelpiano** [comment]
@enicolasgomez what is a rough estimate?
I am ok in postponing the release to get this addressed, I'll double check if an issue for Salva.

**Comment by enicolasgomez** [comment]
@ddelpiano I would say base 8-10hs as it's a two parts problem.

On the other hand #403 is also related to this one so we can grab some time from there. There's a chance that we could fix both.

**Comment by enicolasgomez** [comment]
stability issues has been fixed however, the described issue persists so created #492 after it

**Comment by enicolasgomez** [comment]
@ddelpiano following @filippomc advice, created a RESET_STATE action so it fires up the store's state reset before loading the new model. Seems to be doing the trick.
