### ISSUE TITLE
Prepare a list of changes requested on the GUI to work with the latest version of netpyne

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#439]

**Comment by salvadord** [comment]
working on this but for now Im adding here the list of changes of the last release to use as reference: https://github.com/suny-downstate-medical-center/netpyne/blob/development/CHANGES.md

**Comment by salvadord** [comment]
Started gdoc with list of changes required for GUI here: https://docs.google.com/document/d/1Ftg6sENR952qzJGzDiWWfthbUCVqWU5XPaOhhCloXJo/edit?usp=sharing
