### ISSUE TITLE
instantiation dialog box & GEPPETTO spinner overlap

### ISSUE THREAD

**Issue by rodriguez-facundo** [MetaCell/NetPyNE-UI#44]
when instantiating a network (big enough), the instantiation dialog box that ask if we want to instantiate the network, remains in the background after clicking accept. Meanwhile, the Geppetto spinner appears overlapping with the dialog box given a confusing look:

![screen shot 2018-07-03 at 7 57 09 pm](https://user-images.githubusercontent.com/32278395/42249965-24d6ce62-7efc-11e8-96be-4f84a32a8433.png)

**Comment by adrianq** [comment]
Fixed with https://github.com/MetaCell/geppetto-netpyne/pull/40
