### ISSUE TITLE
web socket ping time out

### ISSUE THREAD

**Issue by rodriguez-facundo** [MetaCell/NetPyNE-UI#45]
while trying to instantiate a medium size network, I get:

![screen shot 2018-07-03 at 9 19 45 pm](https://user-images.githubusercontent.com/32278395/42251786-5c95138a-7f07-11e8-80db-17768042dd53.png)

and the GUI goes white (can't open web inspector)

**Comment by tarelli** [comment]
Valid issue, after CNS
