### ISSUE TITLE
Usability - avoid model initialization, part 2 of the issue 311

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#451]
**New button**
- In the edit view, add a button to go to the explorer view, same styling and position of the button "back to edit" that we have when we are in the explorer view.
- That button should only let the UI transit to the other view, not initialise or simulate anything.
- If the modelState in the redux store is not instatiated the button above should be disabled (since there won't be anything in that view), put a tooltip in the button that says "the model needs to be instantiated in order to display the results in the next view", this text can be tweaked later.
![scrnli_07_03_2022_14-39-30.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/c3c7c460-f723-4ba3-96ab-fd0861090fa6)

**Regarding the existing pink button that allow us to simulate and/or instantiate the network:**
- when the modelState is instantiated or simulated change the default nomenclature we show for the button, from 'create the network' to 'update the network'.
![scrnli_07_03_2022_14-40-38.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/26348a1b-f5a0-4be8-9d46-300ea2896bd5)

**Comment by enicolasgomez** [comment]
@ddelpiano Done. This is how it looks like when no model is instantiated:

![Screen Shot 2022-03-08 at 11.19.18.png](https://images.zenhubusercontent.com/610183f51ec1245011ca9923/41fb6d99-d6b9-4c89-a2bd-f02502c652a9)@ddelpiano 

And these are the two other cases:

![Screen Shot 2022-03-08 at 11.18.10.png](https://images.zenhubusercontent.com/610183f51ec1245011ca9923/a9724923-feab-482b-b002-e27e24b2505c)
![Screen Shot 2022-03-08 at 11.18.06.png](https://images.zenhubusercontent.com/610183f51ec1245011ca9923/512b27ee-4913-4cca-a863-8400aed78cad)

However, for some reason I found some layout issues:

- Cells look squared and without color
- Left toolbar buttons are lost
- When going back to edit view, experiment manager stretches and modifies the layout

![Screen Shot 2022-03-08 at 11.18.19.png](https://images.zenhubusercontent.com/610183f51ec1245011ca9923/25ccaf7f-5212-4cfd-adfd-8018545ddd7f)

![Screen Shot 2022-03-08 at 11.17.55.png](https://images.zenhubusercontent.com/610183f51ec1245011ca9923/bb14f0a1-d0ef-4a64-acdd-d79b3dd12973)

I think it's related to this fix I included after discussing with @vidhya-metacell realted to meaterial-UI version but not really sure:

https://github.com/MetaCell/NetPyNE-UI/commit/aa14f8efd77245a46a8ae3367b511eb2694cad1a#diff-8b46813913d2fb531c456e0bdb12b4b4449a60b82092458043fe778afd1926f4

@vidhya-metacell it's going to be more productive if you see that by yourself running this branch.
