### ISSUE TITLE
Add fields from migration document related to the dipole and LFP plots

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#460]
Document:

https://docs.google.com/document/d/1Ftg6sENR952qzJGzDiWWfthbUCVqWU5XPaOhhCloXJo/edit

**New fields**

To be added to Configuration->Record:

**cfg.recordDipole** = False # record dipoles using lfpykit method
**cfg.recordDipolesHNN** = False # record dipoles using HNN method
**cfg.saveLFPCells** = False  # Store LFP generated individually by each cell (Note, this is already available, check if the key is still the same).
**cfg.saveLFPPops** = False  # Store LFP generated individually by each population
**cfg.saveDipoleCells** = False  # Store LFP generated individually by each cell
**cfg.saveDipolePops** = False  # Store LFP generated individually by each population

To be removed from Configuration->General:

- Check parameter errors
- Check parameter errors verbose mode

**Comment by enicolasgomez** [comment]
@ddelpiano waiting for @salvadord feedback on the slack channel as it seems that the new fields are missing from netpyne's metadata declaration

**Comment by ddelpiano** [comment]
waiting a new netpyne release https://github.com/suny-downstate-medical-center/netpyne/pull/675
