### ISSUE TITLE
Add dipole and EEG plots

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#461]

**Comment by enicolasgomez** [comment]
@ddelpiano while this one has been completed there's still an issue for deployment, if you check this thread:

https://metacell.slack.com/archives/C02UT6WECEL/p1648672583863579

we need a header file for EEG plot to work which is downloaded when this is run (see Computing EEG from dipole moment.)

https://lfpy.readthedocs.io/en/latest/classes.html

we need a mechanism to bundle this file into the UI
