### ISSUE TITLE
Prepare Netpyne-UI 0.8.0 release

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#463]
for Nico:

- github merging to be handled
- github release to be published

for Dario:
- release notes
- final round of testing

**Comment by enicolasgomez** [comment]
@ddelpiano this one is ready:
https://github.com/MetaCell/NetPyNE-UI/pull/498

has latest netypne 102 changes ready to be merged to the 080 release branch
