### ISSUE TITLE
Parameter values not showing in IClamp in Stim Sources tab

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/NetPyNE-UI#467]
@ddelpiano Managed to get the development branch building locally & experiments running, looks good!

Issue though with display of values in IClamp. Load the Tutorial 1, the values for amplitue, etc. are set in the source file, but not showing in the tab, and can't be edited with new values.

<img width="501" alt="Screenshot 2022-03-18 at 10 15 54" src="https://user-images.githubusercontent.com/1556687/158985125-ca4a1f06-5f2d-4773-93fb-2a88158dfcaa.png">

Also an issue when changing to other stim types like NetStim

**Comment by ddelpiano** [comment]
Hi @pgleeson, thx for reporting this.
The values are actually 'digested' but not displayed, we'll look into it this sprint.

**Comment by ddelpiano** [comment]
This is duplicate of #467 , the issue underneath is the same but the manifestation might be different due to the different components linked with the python controlled capabilities.

**Comment by enicolasgomez** [comment]
@ddelpiano this has also been fixed on latest geppetto/development

**Comment by pgleeson** [comment]
Verified that this is fixed in the latest development of NPUI with the latest development of geppetto-meta, so closing. Thanks!
