### ISSUE TITLE
Display & spinner not working in population number

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/NetPyNE-UI#468]
Similar to #467, issues with displaying number of population and editing it, the spinner on the right is also broken and 1 flashes up when you try to change the number up and down:
<img width="866" alt="Screenshot 2022-03-18 at 10 21 47" src="https://user-images.githubusercontent.com/1556687/158986192-5789e43c-6836-45ea-bf6d-c75e0cdac400.png">

This is what it should look like (from the version deployed on OSBv2 - up/down arrows work:
<img width="683" alt="Screenshot 2022-03-18 at 10 25 29" src="https://user-images.githubusercontent.com/1556687/158986336-29ce4860-feea-4240-a7ef-9f8aa08279ca.png">

**Comment by ddelpiano** [comment]
Hi @pgleeson, thx for reporting this.
The values are actually 'digested' but not displayed, we'll look into it this sprint.

**Comment by ddelpiano** [comment]
@enicolasgomez this seems to be coming from jupyter geppetto, I can see in console that the python controlled capability is connecting and disconnecting to/from the component itself, did something changed in that recently?
during the migration to the latest geppetto I've never noticed such issue.

**Comment by ddelpiano** [comment]
@enicolasgomez https://github.com/MetaCell/geppetto-meta/pull/307/commits/936fd462af6834764442c17c389c3abd1780d579 to check if this impacted the sync mechanism somehow, I was looking for something else in my pr and I spotted this

**Comment by enicolasgomez** [comment]
@ddelpiano this has been fixed in lastest geppetto/development

**Comment by ddelpiano** [comment]
@enicolasgomez could you link to the commit/PR that fixed this, please? Thx

**Comment by pgleeson** [comment]
This is fixed with regards to display, but the spinner functionality is broken. It can be clicked and the population size will visibly change, but it reverts back to the previous value immediately...

**Comment by enicolasgomez** [comment]
@ddelpiano that's the one:
https://github.com/MetaCell/geppetto-meta/commit/1703a0450bb64f703c3b6fd284a2c113d3405545
