### ISSUE TITLE
Opening a new model (e.g. a different tutorial) should close the 3D view

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/NetPyNE-UI#479]
When viewing one model in 3D and then opening another, e.g. open a new tutorial, the 3D view of the old model stays visible, even though the new model is opened in memory when you go back to the Edit tab/view.

Simplest might be to change back to the Edit view whenever a new model (even a blank model) is loaded.

**Comment by ddelpiano** [comment]
duplicate of #437
