### ISSUE TITLE
Netpyne model with RxD returning issues when instantiated twice

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#481]
netpyne error returned:

```
Can't clean for JSON: FractionalVolume(volume_fraction=0.8, surface_fraction=1, neighbor_areas_fraction=0.8)
```

**Comment by ddelpiano** [comment]
added a clearAll argument to sim.create() — see here: https://github.com/suny-downstate-medical-center/netpyne/commit/fa7e9763693ba516985b94aaf082eebc49fc3efd

**Comment by ddelpiano** [comment]
@enicolasgomez we need to add the boolean required when we call sim.create on our side.

**Comment by enicolasgomez** [comment]
@ddelpiano added clearAll=true as requested in issue/481_load_rxd_twice_fail - asked @salvadord if there is an official release for this as I pulled netpyne/development in order for this to work
