### ISSUE TITLE
deleteParams propagate fails. Model mismatch.

### ISSUE THREAD

**Issue by enicolasgomez** [MetaCell/NetPyNE-UI#489]
While looking into #437 and attemping to delete the population, propagate_field_rename is called from the initial deleteParam call, this set of conditions fail when some of the parameters are trying to access:

https://github.com/MetaCell/NetPyNE-UI/blob/development/netpyne_ui/netpyne_geppetto.py#L1025

e.g.:

key = "pyr"
cond = "conds"

if you see this line:
https://github.com/MetaCell/NetPyNE-UI/blob/development/netpyne_ui/netpyne_geppetto.py#L987

and this object, conds is not part of pyr so it throws:
`{pyr: {'secs': {'soma': {'geom': {'diam': 12, 'L': 12, 'Ra': 100.0, 'cm': 1}, 'mechs': {'hh': {'gnabar': 0.12, 'gkbar': 0.036, 'gl': 0.0003, 'el': -54.3}}}, 'dend': {'geom': {'diam': 1.0, 'L': 200.0, 'Ra': 100.0, 'cm': 1}, 'mechs': {'pas': {'g': 0.001, 'e': -70}}, 'topol': {'parentSec': 'soma', 'parentX': 1.0, 'childX': 0}}}}}`

Calls my attention that it fails for almost any attempt to propagate so I was wondering if this something known? should we spend time on this?

@ddelpiano @filippomc

**Comment by filippomc** [comment]
agreed that `propagate_field_rename` shoud be checked and made more robust as an error may leave the model in an unconsistent state.
Need also to understand if conds is supposed to be there in the beginning

**Comment by ddelpiano** [comment]
addressed by the last PR opened by Nico (discussed at the internal sprint call).
