### ISSUE TITLE
Import cell template with shared folder in Docker doesn't work

### ISSUE THREAD

**Issue by salvadord** [MetaCell/NetPyNE-UI#49]
when I try to import either a .hoc or .py cell template (+ compile) from Docker, it doesn't do anything (probably a try / except block?)  
I tried PTcell.hoc and PTcell.py

**Comment by adrianq** [comment]
There is probably an exception but it is not being handled properly. This is also solved in the development, in particular in this commit https://github.com/MetaCell/geppetto-netpyne/pull/35/commits/08bd89725b73ceac3a8988b3c40fbc89c7b09991 Any chances you use the development version as this is not part of the docker image yet?

**Comment by salvadord** [comment]
yes, works ok in the development version I have locally.
So, the only problem is I cannot try/fix the h.load_file() issue until this is fixed in the Docker version.
