### ISSUE TITLE
Name of downloaded files comes from visualisation library

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [MetaCell/NetPyNE-UI#516]
When downloading a plot created, the name of the downloaded file is bokeh.png for all of them (name coming from the visualisation library)
 ![image4.png](https://images.zenhubusercontent.com/6205315492e76e1daec1fb25/b983089b-5b05-4b44-ab09-357d959c9d6e)

**Comment by ddelpiano** [comment]
not possible from the GUI, this would it be a card for netpyne but I don't see this as a bug, rather an enhancement.
