### ISSUE TITLE
'Save to json file' dialog options ignored

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [MetaCell/NetPyNE-UI#518]
On the 'save to json file' feature I am not sure if the options to be ticked (netParams, simConfig, instantiated network and simulation data) are being applied. 

To have something I selected the tutorial 1 and prior to creating or simulating the network I saved it as: a json file ticking everything available (simConfig and netParams) (outputticked....json) and a json file with nothing ticked (outputnot...json). 
Since it is not a too long of a json file I checked the data and it looks like they're the exact same 

https://images.zenhubusercontent.com/122103040/0a5dc665-5782-4e17-8ea9-247019bb9a32/screen_recording_2022_05_18_at_12_04_52.mov

and the json files should be different.

**Comment by ddelpiano** [comment]
parking this to avoid redundancy with the file format

**Comment by salvadord** [comment]
should be easy to solve... I assume you call the `sim.saveData()` function in netpyne ... this function has an argument `include=[...]` which takes any subset of these options: 'simConfig', 'netParams', 'net', 'simData' (corresponding to the options in the dialog)
