### ISSUE TITLE
Error dialog misleading button functionalities

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [MetaCell/NetPyNE-UI#519]
When opening a json file and not selecting any of the options available pops up a message saying you need to select at least one option. 

Along with it there's the 'Back' and 'Cancel' buttons, which one should lead you to the previous box with the options to choose from and the other should close it, respectively. 

Pressing either of those closes the 'open json file' box

https://images.zenhubusercontent.com/122103040/345d7cd6-7455-4af4-8285-c25ff0b66232/screen_recording_2022_05_17_at_09_49_22.mov

**Comment by ddelpiano** [comment]
- remove one button (the cancel one ideally)
- change nomenclature for the other button from 'Back' to 'Close'

**Comment by aranega** [comment]
@ddelpiano The error message is built from a generic `ActionDialog`. It seems that the default behavior for this is to go `Back` when an error is raised. There is some cases where and error actually allows to come back? If yes, I can try to pass an additional information from Python to JS to say that the this error `canGoBack`, if no, I just change the label for the button. What would be the best?
