### ISSUE TITLE
Error plotting EEG due to missing NY head model

### ISSUE THREAD

**Issue by salvadord** [MetaCell/NetPyNE-UI#527]
(I might not be using the latest version so this might be fixed already)

<img width="942" alt="image" src="https://user-images.githubusercontent.com/8440562/169624226-8d958375-fbd4-49de-9110-8c9a776c4003.png">

**Comment by salvadord** [comment]
this is a 500mb file that needs to be added to the lfpykit repo... when running this programmatically the code asks if you want to downloaded

**Comment by enicolasgomez** [comment]
@ddelpiano check this thread:

https://metacell.slack.com/archives/C02UT6WECEL/p1648672583863579

Basically, if you run this in the console it will ask you to download de 500mb file 

@salvadord sorry Salva, you mentioned that needs to be added to lfpykit but my understanding is that it's already there and we should find the way to add it to the UI bundle?

**Comment by salvadord** [comment]
https://www.parralab.org/nyhead/sa_nyhead.mat

https://github.com/LFPy/LFPykit/blob/a3165908eb25f2b327c49e3ef30c69c6df4ceb8c/lfpykit/eegmegcalc.py#L1398

**Comment by salvadord** [comment]
@enicolasgomez discussed this with dario & co at meeting -- they can update you

**Comment by salvadord** [comment]
@filippomc @enicolasgomez what was the final solution? is the file included at startup?

**Comment by filippomc** [comment]
@salvadord

**Comment by salvadord** [comment]
@filippomc thanks. I believe the path is hard coded in lfpykit, so not sure can set a different one, but we can check the lfpykit code.

**Comment by filippomc** [comment]
Yes can pass a different path to the [NYHeadModel](https://lfpykit.readthedocs.io/en/latest/#class-eegmegcalc-nyheadmodel) constructor
