### ISSUE TITLE
Python script generated by File->Export->To python not valid

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/NetPyNE-UI#530]
Line 4 gives an error:

<img width="752" alt="Screenshot 2022-05-25 at 12 07 49" src="https://user-images.githubusercontent.com/1556687/170248791-bda25ae6-7295-4d45-af8b-e145e5ed4f86.png">

**Comment by pgleeson** [comment]
Also ids/names of populations etc. not enclosed in quotes:

<img width="431" alt="Screenshot 2022-05-25 at 12 12 06" src="https://user-images.githubusercontent.com/1556687/170249434-e2028c17-69a2-4cec-93e6-2f800b9d9356.png">

**Comment by salvadord** [comment]
https://github.com/suny-downstate-medical-center/netpyne/blob/development/netpyne/conversion/pythonScript.py

**Comment by vvbragin** [comment]
@pgleeson https://github.com/MetaCell/NetPyNE-UI/pull/534

**Comment by pgleeson** [comment]
Thanks @vvbragin. I had an inkling it had been fixed elsewhere...

**Comment by salvadord** [comment]
so this solves the issue? was it tested with the GUI? @ddelpiano @filippomc

**Comment by ddelpiano** [comment]
> so this solves the issue? was it tested with the GUI? @ddelpiano @filippomc

@salvadord this is on us, I already sorted this locally, myself and filippo are working on the priority issues you flagged so this/next week we will get them sorted.
