### ISSUE TITLE
in Experiment Explorer stimTargetParams conditions not there 

### ISSUE THREAD

**Issue by salvadord** [MetaCell/NetPyNE-UI#533]
<img width="782" alt="image" src="https://user-images.githubusercontent.com/8440562/170375774-4cdd518a-67fc-4435-8f7e-5f465b0ba21c.png">

**Comment by filippomc** [comment]
fixed: ![image](https://user-images.githubusercontent.com/46561561/183905459-75c98047-411b-4911-a491-e153bde92288.png)
