### ISSUE TITLE
cell mechanisms don't show as circles

### ISSUE THREAD

**Issue by salvadord** [MetaCell/NetPyNE-UI#535]
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/8440562/170507093-ca4cc8f3-dbd1-4951-8898-7ae66fb7189a.png">

**Comment by pgleeson** [comment]
Similar is happenning with plots...

<img width="568" alt="Screenshot 2022-05-26 at 15 35 59" src="https://user-images.githubusercontent.com/1556687/170510391-bc05f46a-df5d-42d4-bab2-437d6f9d054f.png">

**Comment by ddelpiano** [comment]
opened here https://github.com/OpenSourceBrain/OSBv2/issues/509
