### ISSUE TITLE
Visualization issue while exploring results w/ experiment manager

### ISSUE THREAD

**Issue by kelley92** [MetaCell/NetPyNE-UI#539]
I start viewing a plot from one of the experimental conditions (screenshot1.png), 

![screenshot1](https://user-images.githubusercontent.com/6529904/170513316-816dbc03-73f7-4f6e-91a4-9ee5214aaeb5.png)

click on 'Explore results' for a different experimental condition, and both the experiment manager and plotting tabs go blank:

![screenshot2](https://user-images.githubusercontent.com/6529904/170513314-0c73d966-689b-46a2-8948-04ce6068df8f.png)

**Comment by ddelpiano** [comment]
As tested by @r-makarov we found out that the problem can solved editing the defaultLayout.js in netpyne with some extra params that would avoid the user to hack the bottom border (that should not be used in that way) - @r-makarov could you add the latest version of the defaultLayout you used for future reference please?

this issue however cannot be fixed until we fix [this](https://github.com/MetaCell/geppetto-meta/issues/287) (priority bumped up)!

**Comment by r-makarov** [comment]
In `webapp/components/layout/defaultLayout.js` `borderEnableDrop: false` and/or `enableDrop: false` should be added

```
export default {
  global: {
    sideBorders: 8,
    tabSetHeaderHeight: 26,
    tabSetTabStripHeight: 26,
    enableEdgeDock: false,
    borderBarSize: 0,
    borderEnableDrop: false,
  },
  borders: [
    {
      type: 'border',
      location: 'bottom',
      children: [],
      enableDrop: false,
    },
  ],
  layout: {
    type: 'tabset',
    weight: 100,
    id: 'root',
    children: [],
  },
};
```
