### ISSUE TITLE
Add basic recordTraces by default

### ISSUE THREAD

**Issue by salvadord** [MetaCell/NetPyNE-UI#546]
can include this one by default: V_soma: {sec: soma, loc: 0.5, var: v}

then the user only needs to specify which cell to record from.

if no cells are selected, then nothing happens.

**Comment by salvadord** [comment]
Need to add this line when new models are created from scratch (i.e. at startup and when user clicks File -> New):

`netpyne_geppetto.simConfig.recordTraces = {'V_soma': {'sec':'soma', 'loc':0.5, 'var':'v'}}`

**Comment by ddelpiano** [comment]
already part of development https://github.com/MetaCell/NetPyNE-UI/blob/cd42eaa52fc36257950f15db00390c8c5f24f4cf/netpyne_ui/netpyne_geppetto.py#L57
