### ISSUE TITLE
Remove references to icons inside node_modules

### ISSUE THREAD

**Issue by filippomc** [MetaCell/NetPyNE-UI#553]
Netpyne is still using geppetto icons and fontAwesome icons from the node_modules folder.
It would be better to replace these icons or to import/copy those icons during the build.

**Comment by filippomc** [comment]
Some pointers:
- https://github.com/MetaCell/NetPyNE-UI/blob/fb1dbcbfb94c6db2b5c17e6c327c1d4a8e49b63c/webapp/geppetto.ejs#L21 css files imported
- only icon used native from Geppetto is gpt-fullgear
- fontawesome also comes from Geppetto, can be just added to Netpyne

A quick win can also be adding a copy task on webpack to get the same files without the need of keeping the node_modules reference

**Comment by aranega** [comment]
@filippomc I'm working on the issue and I went with [this modifications](https://github.com/MetaCell/NetPyNE-UI/commit/c754a3c35b74960c6e606f93cb4cd22ff85bbd89) 

Am I in the right direction or do I miss something more? (or did I misunderstand the issue)

**Comment by filippomc** [comment]
Hey @aranega yes this approach should work, better make sure that the copied resources are part of the geppetto bundle and do the same for all other references. After this is done, can remove the node_modules copy from the dockerfile https://github.com/MetaCell/NetPyNE-UI/blob/fb1dbcbfb94c6db2b5c17e6c327c1d4a8e49b63c/Dockerfile#L17

**Comment by aranega** [comment]
Hey @filippomc ! Thanks for the details :), I'll pass on all of that fix the last points. Thanks again!
