### ISSUE TITLE
Add menu items in UI for loading NeuroML/LEMS 

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/NetPyNE-UI#560]
@filippomc @ddelpiano I've added 2 helper methods in this script [here](https://github.com/OpenSourceBrain/NetPyNEShowcase/blob/master/NetPyNE/UI/helpers.py):`convertAndImportNeuroML2(nml2FileName)` and `convertAndImportLEMSSimulation(lemsFileName)`, which are self contained methods for loading in A) a NeuroML file, or B) a [LEMS Simulation file](https://docs.neuroml.org/Userdocs/LEMSSimulation.html), converting them to the NetPyNE equivalent, including mod file, compiling the mods and generating the JSON equivalent which I've tested can easily be loaded using the current JSON loader. They also return the `netParams` and `simConfig`.

Hopefully these should be sufficient for adding to NetPyNE-UI (as `neuroml_utlis.py` in [here](https://github.com/MetaCell/NetPyNE-UI/tree/master/netpyne_ui)?), and then 2 extra options added to the menu:

<img width="593" alt="Screenshot 2022-06-15 at 13 28 27" src="https://user-images.githubusercontent.com/1556687/173826884-4c965e31-c935-45cf-b1cf-78fcc4e50be1.png">

**From NeuroML2...** (opening a dialog to find any file *.net.nml) 
**From LEMS Simulation...** (finding any file *.xml) 

which ultimately call these methods in Python, and load the model. 

How would that sound? The helper methods could eventually be moved to core netpyne, but keeping them here for now would just aid testing/deployment etc.

**Comment by filippomc** [comment]
@salvadord how does it sound adding these two import options to you?

**Comment by filippomc** [comment]
We are able now to import a neuroml model in the gui, but the kernel crashes as soon as we try to do anything with the simulation: either `sim.clearAll()`, `sim.initialize()` or `sim.create(...)` cause a crash.
If we load the generated json on a new kernel we are able to instantiate and simulate.

May be something related to how the sim is created in importNeuroML2 @salvadord?

**Comment by pgleeson** [comment]
@filippomc I've updated the format of the python script that pyneuroml generates (https://pypi.org/project/pyNeuroML/0.7.1/ required) as well as adding an option to generate the full netpyne json representation, plus the mod files all from the one pyneuroml call. I've updated the helpers.py to reflect this: https://github.com/OpenSourceBrain/NetPyNEShowcase/blob/master/NetPyNE/UI/helpers.py#L19

This should mean that in npui, you can call this method, delete the generated x86_64 (the mod files are compiled  and loaded in a separate process than the current kernel), and then load the json/compile the mods in an identical manner to the case where a user specified the json/mods.

**Comment by filippomc** [comment]
Related: allow for xml and nml files to be uploaded from the ui

**Comment by pgleeson** [comment]
@filippomc Testing this again... Is the latest version deployed at v2dev? Getting the following error while importing Spikers.net.nml:

<img width="1440" alt="Screenshot 2022-07-26 at 11 25 16" src="https://user-images.githubusercontent.com/1556687/180984658-b66ffc48-b4ad-44bc-af3b-222ef0b2c2fe.png">

**Comment by pgleeson** [comment]
On a related note, last time we were looking for a Netpyne json+mods example to test loading different ways.

This example: https://github.com/OpenSourceBrain/NetPyNEShowcase/blob/master/NeuroML2/multicomp/DendConn.txt_data.json plus the mod files in that folder can be successfully loaded/simulated using the JSON load option in the UI (with compile mods)

The equivalent NML in the same directory is failing (but for the same reason as above...).
