### ISSUE TITLE
Control panel disappeared

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [MetaCell/NetPyNE-UI#562]
The Control panel which allows you to hide, change colors and zoom in to specific networks is no longer visible

Environment Tested: http://34.71.18.84/
<img width="1331" alt="Screenshot at Jun 17 10-03-21" src="https://user-images.githubusercontent.com/99416933/174265934-cd3b5ad6-5da9-4d95-a4fe-de6041ae335e.png">

Expected:
<img width="1184" alt="Screenshot at Jun 17 10-03-37" src="https://user-images.githubusercontent.com/99416933/174265900-09e0b626-d5b2-40a0-82a7-aac504cb9e24.png">

**Comment by filippomc** [comment]
The control panel has now moved to a different place and behaviour. See #417 
![image](https://user-images.githubusercontent.com/46561561/174979327-d6004a88-f357-4948-ab8e-cf4391adb060.png)
