### ISSUE TITLE
SynMechParams don't show up sometimes (see CNS22 video)

### ISSUE THREAD

**Issue by salvadord** [MetaCell/NetPyNE-UI#573]

**Comment by salvadord** [comment]
I couldn't find it in the video, but I coudl reproduce part of the problem in the current v2.osb netpyne ui 

If you load tut 3a and you go to synMechParams panel, the parameters of the exc and inh mechs are not there (see fig)
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/8440562/203394557-aa30a613-3bb0-46a9-9738-eac74b1fa0a8.png">

**Comment by ddelpiano** [comment]
thanks @salvadord , I can reproduce the problem on v2, we'll keep you posted.

**Comment by ddelpiano** [comment]
https://images.zenhubusercontent.com/122103040/4332b9d8-b30a-42f4-9e7f-395dcf81d23a/scrnli_23_11_2022_10_13_33.mp4

**Comment by ddelpiano** [comment]
@aranega I can see this happening on [stage](https://stage.netpyne.metacell.us/) as well (if prompted with user and password type test test on stage)

**Comment by SimaoBolota-MetaCell** [comment]
```diff
+ TESTED SUCCESSFULLY
```

When loading the tutorial 3a, the parameters of the **exc** and **inh** Synaptic Mechanisms are always present, even by clicking the mechs a couple of times, as seen in the screen recording below

https://user-images.githubusercontent.com/99416933/208717322-b1008eb4-3f3a-4257-b621-9118d377345a.mov
