### ISSUE TITLE
"Choose files" button not working for some people

### ISSUE THREAD

**Issue by kelley92** [MetaCell/NetPyNE-UI#578]
A student using netpyne through open source brain (v2.opensourcebrain.org/, chrome browser, macbook pro) was unable to upload files because the "Choose files" button under File->Workspace->Upload was unresponsive.  It did work, however, when she tried using Safari as the browser.

**Comment by ddelpiano** [comment]
@filippomc this seems related to the workspace, if you agree I would move this to the OSB repo - Thanks
