### ISSUE TITLE
Upgrade to the latest netpyne version

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#584]
for @enicolasgomez :

- ~~re-enable netpyne-ui test environment on codefresh~~ https://test.netpyne.metacell.us/
- prepare branch on the netpyne-ui
- upgrade to the latest version of netpyne (to be provided by @salvadord)
- deploy the above
- notify @ddelpiano and @SimaoBolota-MetaCell , we'll handle the testing and report back in this card.

**Comment by ddelpiano** [comment]
https://app.zenhub.com/workspaces/netpyne---metacell-board-5bd615394b5806bc2bef3799/issues/metacell/netpyne-ui/581 to keep this under the radar since noticed when using the latest netpyne

**Comment by enicolasgomez** [comment]
@ddelpiano created new branch feature/584_netpyne_103 which contains netpyne 103, did an overall testing and all good. Maybe we can get @SimaoBolota-MetaCell involved ?

**Comment by enicolasgomez** [comment]
Note: that branch is branched from release/081 so it includes all latest stuff

**Comment by ddelpiano** [comment]
taking it over for review, thx @enicolasgomez
