### ISSUE TITLE
Unable to simulate 3 conditions in Tut 4: Simple Oscillatory Network using experiment manager

### ISSUE THREAD

**Issue by smcelroy97** [MetaCell/NetPyNE-UI#608]
Followed along the CNS 22 video, simulation ran fine initially using NetPyNE GUI on OSB. When I added 3 values for Inh Tau 2 the experiment was never able to finish and was stuck simulating. Opened OSB and where it had said simulating earlier it now says ERROR

**Comment by ddelpiano** [comment]
it seems related to the same issue flagged and fixed with 0.9.1, closing
