### ISSUE TITLE
Experiments not working in release/0.9.0

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#632]
Testing the experiment with the latest it does not work properly, flow followed.

- load tutorial 1
- go to experiment manager
- create a new experiment
- set the parameter of netParams.popParams.E.numCells, from 10 to 13, step 1
- click create bottom right
- select simulate from the top-right corner
- click simulate, modal will appear, click on All trials (3)
- the experiment manager will change state and will stay always in pending.

checking the results and error in the workspace/experiments folders I can see this

test-1-1_0.run (note on this, there was also an error for a missing package, optuna, that i installed in my virtualenv, you will see this error as well the first time).
```
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file /home/ddelpiano/git/netpyne-ui/workspace/experiments/test-1-1/test-1-1_0_cfg.json ... 
Loading simConfig...
Trial failed ...
[Errno 2] No such file or directory: '/home/ddelpiano/git/netpyne-ui/workspace/experiments/test-1-1/test-1-1_netParams.py'
```

test-1-1_0.err
```
NEURON -- VERSION 7.8.1-1-gda13bb7c HEAD (da13bb7c) 2020-07-22
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2019
See http://neuron.yale.edu/neuron/credits

dlopen failed - 
../../../x86_64/.libs/libnrnmech.so: undefined symbol: _nrnunit_use_legacy_
0 /home/ddelpiano/miniconda3/envs/netpyne/bin/nrniv: can't open simConfig=/home/ddelpiano/git/netpyne-ui/workspace/experiments/test-1-1/test-1-1_0_cfg.json
Could not open netParams=/home/ddelpiano/git/netpyne-ui/workspace/experiments/test-1-1/test-1-1_netParams.py
```

checking the files, the simConfig seems to be there but the netParams no.

**Comment by enicolasgomez** [comment]
@ddelpiano I couldn't verify that netParams was missing in my case all the files were there and the run.py file make sense. I was able to find an exception related to the simulation run though:
```

[mpiexec@Eduardos-MacBook-Pro.local] match_arg (utils/args/args.c:163): unrecognized argument use-hwthread-cpus
[mpiexec@Eduardos-MacBook-Pro.local] HYDU_parse_array (utils/args/args.c:178): argument matching returned error
[mpiexec@Eduardos-MacBook-Pro.local] parse_args (ui/mpich/utils.c:1639): error parsing input array
[mpiexec@Eduardos-MacBook-Pro.local] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1691): unable to parse user arguments
[mpiexec@Eduardos-MacBook-Pro.local] main (ui/mpich/mpiexec.c:127): error parsing parameters
```
this exception is thrown from MPI which is a parallel computing library which neruon uses internally, not sure yet what got disconnected.

I tried rolling back to netpyne-1.0.2.1 to check if it's related to latest and was able to reproduce the issue.

**Comment by enicolasgomez** [comment]
it's for some reason the local openmpi version (4.0.2) which fails, replicated it running this command manually

```
(base) infectuz@Eduardos-MacBook-Pro test22222 % mpirun -- use-hwthread-cpus 4
[mpiexec@Eduardos-MacBook-Pro.local] match_arg (utils/args/args.c:163): unrecognized argument 
[mpiexec@Eduardos-MacBook-Pro.local] HYDU_parse_array (utils/args/args.c:178): argument matching returned error
[mpiexec@Eduardos-MacBook-Pro.local] parse_args (ui/mpich/utils.c:1639): error parsing input array
[mpiexec@Eduardos-MacBook-Pro.local] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1691): unable to parse user arguments
[mpiexec@Eduardos-MacBook-Pro.local] main (ui/mpich/mpiexec.c:127): error parsing parameters
```

so it seems that Neuron passes the argument correctly but this version fails to recognize the argument.

**Comment by enicolasgomez** [comment]
Atter upgrading  OpenAPI from 4.0.2 to 4.1.4 it succeeded.

![Screen Shot 2022-12-21 at 13.05.17.png](https://images.zenhubusercontent.com/610183f51ec1245011ca9923/14e1aad5-e4b3-49f9-af92-ddb0255f6b87)

**Comment by enicolasgomez** [comment]
![Screen Shot 2022-12-21 at 13.06.39.png](https://images.zenhubusercontent.com/610183f51ec1245011ca9923/e77d45bf-4e62-4d57-8618-7bb3c117b2df)

**Comment by ddelpiano** [comment]
optuna 3.0.5 it is fine.
