### ISSUE TITLE
sa_nyhead.mat missing when plotting EEG from jupyter lab 

### ISSUE THREAD

**Issue by salvadord** [MetaCell/NetPyNE-UI#649]
Even though the first time you run it it asks you to download the file, the file is downloaded to the local folder and it still doesn't work.

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/8440562/210910827-8ba51ed5-5a69-40a7-8da8-8c000b6e9fd5.png">

**Comment by ddelpiano** [comment]
@filippomc this is more related to OSB I believe, for netpyne we are downloading the package and placing it in the [depedency folder](https://github.com/MetaCell/NetPyNE-UI/blob/0d1866394b2eec1f76f55d909596a4fa2a63a765/Dockerfile#L55).
