### ISSUE TITLE
EEG plot not working in GUI

### ISSUE THREAD

**Issue by salvadord** [MetaCell/NetPyNE-UI#653]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/8440562/211404459-a1a34938-0574-4cdb-b2cd-7cd1e248928d.png">

**Comment by ddelpiano** [comment]
- load tutorial 1
- open the configuration tab
- open the record sub-tab
- check the option on the right 'Record dipoles using lfpykit method'
- instantiate and simulate
- from the left sidebar open the eeg plot (2nd from the end of the plots list).

some historical information, right now the build relies on the NYHead model being downloaded during the docker build (check the netpyne-ui dockerfile) and placed in the lfpykit dependency folder, but apparently atm is not working anymore.
