### ISSUE TITLE
docker installation issue

### ISSUE THREAD

**Issue by tschatteman** [MetaCell/NetPyNE-UI#66]
I am trying to install and run docker on a pc running 64 bit windows 10 home.  Docker begins installing and continues through the white screen with the blue 3d box.  After a long wait and multiple requests for permission (which I gave), it failed due to an unexpected error in kitematic (stderr maxBuffer exceeded.)

My computer is a Samsung ATIV with an Intel Core i7-45000 CPU @ 1.80 GHz  2.40 GHz, 8 GB RAM

I would appreciate your help in installing docker.

Tracy Schatteman
tscha3@uis.edu

**Comment by puneethchidura123** [comment]
i am also facing the same issue.  Can some one please help to resolve this.

**Comment by tarelli** [comment]
@tschatteman @puneethchidura123 that seems to be a problem with Kitematic https://docs.docker.com/kitematic/known-issues/
