### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/NetPyNE-UI#68]
Have managed to get it running locally (from master branch), looks good. Some initial thoughts:

- [x] Add option to load some standard models (e.g. M1) & prefill netParams/simParams/paths etc.
- [ ] Add shutdown NetPyNE/kernel option in gui (which also closes tab), so user is sure they shutdown cleanly & the command line can be halted.
- [x] Python console doesn't seem to work...

**Comment by lrebscher** [comment]
Closes in favor of #228
