### ISSUE TITLE
Mismatch in Neuron version in about box

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/NetPyNE-UI#702]
<img width="1034" alt="Screenshot 2023-04-11 at 14 18 28" src="https://user-images.githubusercontent.com/1556687/231175256-bb5e0c27-c8fb-4563-b930-7e89e43e2a75.png">

**Comment by ddelpiano** [comment]
osb is using a preliminary version of the next netpyne release, we usually bump all these versions to the correct one as last thing before the release is tagged and officially finished, right now we are waiting another netpyne release to fix the plots using lfpykit issue and then we'll do it. Thx for flagging it
