### ISSUE TITLE
Examples/tutorials missing from netpyne.opensourcebrain.org - when user logged in to OSB

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/NetPyNE-UI#769]
Used to be listed here:
![Screenshot 2023-10-31 at 16 31 45](https://github.com/MetaCell/NetPyNE-UI/assets/1556687/ed37547c-bc32-4c04-a45f-8aece215a620)

**Comment by pgleeson** [comment]
Correction... This list is only missing if a user is logged in on OSB in another tab. If it is an anonymous user it's fine and the examples show. 
@filippomc Seems to be an unexpected consequence of reusing the application from osb for the standalone application(s)...

**Comment by filippomc** [comment]
Yes that's the problem indeed. Have to agree on what's the correct behaviour when a user is logged-in.

**Comment by pgleeson** [comment]
Fixed now on live
