### ISSUE TITLE
_loadFile not working with py3

### ISSUE THREAD

**Issue by rodriguez-facundo** [MetaCell/NetPyNE-UI#79]
line 69  in netpyne.sim.load.py  uses the object_hook to convert a string that is Unicode into binary type `data = json.load(fileObj, object_hook=_byteify)`
that works for python 2 because there is a difference between string and Unicode, but py3 adopted Unicode as standard 

netpyne PR: https://github.com/Neurosim-lab/netpyne/pull/381
trello card: https://trello.com/c/Q260hAZC/318-loadfile-not-working-for-py3

**Comment by adrianq** [comment]
Solved here https://github.com/Neurosim-lab/netpyne/pull/381
